// apps/demos/Demos/Scheduler/Templates/Vue/AppointmentTooltipTemplate.vue
<template>
  <div class="movie-info">
    <div class="movie-preview-image">
      <img
        :src="movieData.image"
        :alt="movieData.text"
      >
    </div>
    <div class="movie-details">
      <div class="title">
        {{ movieData.text }} ({{ movieData.year }})
      </div>
      <div>
        Director: {{ movieData.director }}
      </div>
      <div>
        Duration: {{ movieData.duration }} minutes
      </div>
    </div>
  </div>
</template>
<script setup lang="ts">
import { query as Query } from 'devextreme-vue/common/data';
import DxScheduler, { type DxSchedulerTypes } from 'devextreme-vue/scheduler';
import { moviesData } from './data.ts';

const props = defineProps<{
  scheduler?: DxScheduler['instance']
  templateTooltipModel?: DxSchedulerTypes.AppointmentTooltipTemplateData
}>();

const getMovieById = function (resourceId: string) {
  return Query(moviesData)
    .filter(['id', resourceId])
    .toArray()[0];
};
const movieData = getMovieById(props.templateTooltipModel?.appointmentData.movieId);
</script>

// Demos/Scheduler/CustomTemplates/React/AppointmentTooltipTemplate.js
import React from 'react';
import Query from 'devextreme/data/query';
import 'devextreme/localization/globalize/date';

import Globalize from 'globalize';

import { moviesData } from './data.js';

function getMovieById(id) {
  return Query(moviesData).filter(['id', id]).toArray()[0];
}

export default class AppointmentTooltipTemplate extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      movieData: getMovieById(props.model.appointmentData.movieId)
    };
    Globalize.locale('en');
  }

  render() {
    const { movieData } = this.state;
    return (
      <div className="movie-tooltip">
        <img src={movieData.image} />
        <div className="movie-info">
          <div className="movie-title">
            {movieData.text} ({movieData.year})
          </div>
          <div>
            Director: {movieData.director}
          </div>
          <div>
            Duration: {movieData.duration} minutes
          </div>
        </div>
      </div>
    );
  }
}
