// Demos/Scheduler/CellTemplates/React/DataCell.js
import React from 'react';
import Utils from './utils.js';

export default function DataCell(props) {
  const { startDate, text } = props.itemData;
  const isDisableDate = Utils.isHoliday(startDate) || Utils.isWeekend(startDate);
  const isDinner = Utils.isDinner(startDate);
  const cssClasses = [];

  if(isDisableDate) {
    cssClasses.push('disable-date');
  } else if(isDinner) {
    cssClasses.push('dinner');
  }

  return (
    <div className={cssClasses}>
      {text}
    </div>
  );
}

// Demos/Scheduler/CellTemplates/Vue/DataCell.vue
<template>
  <div :class="markDataCell(cellData)">
    {{ cellData.text }}
  </div>
</template>
<script>
import Utils from './utils.js';

export default {
  props: {
    cellData: {
      type: Object,
      default: () => {}
    }
  },
  methods: {
    markDataCell(cellData) {
      const date = cellData.startDate;
      const isDisableDate = Utils.isHoliday(date) || Utils.isWeekend(date);
      const isDinner = Utils.isDinner(date);

      return {
        'disable-date': isDisableDate,
        'dinner': isDinner
      };
    }
  }
};
</script>
