// apps/demos/Demos/Scheduler/CellTemplates/ReactJs/TimeCell.js
import React from 'react';
import Utils from './utils.js';

const TimeCell = (props) => {
  const { date, text } = props.data;
  const isDinner = Utils.isDinner(date);
  const hasCoffeeCupIcon = Utils.hasCoffeeCupIcon(date);
  return (
    <div className={isDinner ? 'dinner' : undefined}>
      {text}
      {hasCoffeeCupIcon && <div className="cafe" />}
    </div>
  );
};
export default TimeCell;

// Demos/Scheduler/CellTemplates/Vue/TimeCell.vue
<template>
  <div :class="markTimeCell(cellData)">
    {{ cellData.text }}
    <div
      v-if="hasCoffeeCupIcon"
      class="cafe"
    />
  </div>
</template>
<script>
import Utils from './utils.js';

export default {
  props: {
    cellData: {
      type: Object,
      default: () => {},
    },
  },
  computed: {
    isDinner() {
      const { date } = this.cellData;
      return Utils.isDinner(date);
    },
    hasCoffeeCupIcon() {
      const { date } = this.cellData;
      return Utils.hasCoffeeCupIcon(date);
    },
  },
  methods: {
    markTimeCell(cellData) {
      return { dinner: Utils.isDinner(cellData.date) };
    },
  },
};
</script>
