// apps/demos/Demos/TabPanel/DragAndDrop/React/EmployeeTemplate.tsx
import React from 'react';
import { List } from 'devextreme-react/list';
import service from './data.ts';
import type { Employee, Task } from './data.ts';

function itemRender(data: Task) {
  return <div>{data.Subject}</div>;
}

interface EmployeeTemplateProps {
  data: Employee;
}

function EmployeeTemplate(props: EmployeeTemplateProps) {
  const tasks = service
    .getTasks()
    .filter((task: { EmployeeID: any; }) => task.EmployeeID === props.data.ID);
  const {
    FirstName, LastName, Picture, Position, Notes,
  } = props.data;
  const completedTasks = tasks.filter((task: { Status: string; }) => task.Status === 'Completed');

  return (
    <React.Fragment>
      <div className="employeeInfo">
        <img alt={`${FirstName} ${LastName}`} className="employeePhoto" src={Picture} />
        <p className="employeeNotes">
          <b>{`Position: ${Position}`}</b>
          <br />
          {Notes}
        </p>
      </div>
      <div className="caption">{`${FirstName} ${LastName}'s Tasks:`}</div>
      <div className="task-list">
        <List
          dataSource={tasks}
          showSelectionControls={true}
          selectedItems={completedTasks}
          disabled={true}
          selectionMode="multiple"
          itemRender={itemRender}
        ></List>
      </div>
    </React.Fragment>
  );
}

export default EmployeeTemplate;

// apps/demos/Demos/TabPanel/SortableClosableTabs/Vue/EmployeeTemplate.vue
<template>
  <div>
    <div class="employeeInfo">
      <img
        class="employeePhoto"
        :alt="employee.FirstName + ' ' + employee.LastName"
        :src="employee.Picture"
      >
      <p class="employeeNotes"><b>Position: {{ employee.Position }}</b><br>{{ employee.Notes }}</p>
    </div>
    <div class="caption">{{ employee.FirstName }} {{ employee.LastName }}'s Tasks: </div>
    <div class="task-list">
      <DxList
        :data-source="dataSource"
        :show-selection-controls="true"
        :selected-items="completedTasks"
        :disabled="true"
        selection-mode="multiple"
      >
        <template #item="{ data: item }">
          <div>
            {{ item.Subject }}
          </div>
        </template>
      </DxList>
    </div>
  </div>
</template>
<script setup lang="ts">
import DxList from 'devextreme-vue/list';
import service from './data.ts';

const props = withDefaults(defineProps<{
  employee?: Record<string, any>
}>(), {
  employee: () => ({} as Record<string, any>),
});

const tasks = service.getTasks();
const employeeTasks = tasks.filter(({ EmployeeID }) => EmployeeID === props.employee.ID);
const dataSource = employeeTasks;
const completedTasks = employeeTasks.filter(({ Status }) => Status === 'Completed');
</script>
<style>
.caption {
  padding: 0 0 10px 30px;
  font-size: 14px;
  font-weight: bold;
}

.task-list {
  padding: 0 20px;
}

.task-list .dx-state-disabled {
  opacity: 1;
}

.task-list .dx-state-disabled .dx-list-item {
  opacity: 1;
}
</style>
