// packages/react/src/components/pager/views/dxPagerPageNumberView.tsx
import React from 'react';
import { PageNumberReactVM } from '../types/public/index';

interface DxPagerPageNumberViewProps {
    // TODO jQuery: Temporary wrapping for the inferno generator.
    data: {
        viewModel: PageNumberReactVM;
        selectPage: (pageNumber: number) => void;
    }
}

const DxPagerPageNumberView = ({
    data: {
        viewModel,
        selectPage
    }
}: DxPagerPageNumberViewProps) => {
    return (
        <div className="dx-pager-pages">
            {
                viewModel.items.map((item) =>
                    item.template({
                        data: {
                            item,
                            selectPage
                        }
                    })
                )
            }
        </div>
    );
};

export type { DxPagerPageNumberViewProps };
export { DxPagerPageNumberView };

// packages/angular/projects/angular/src/components/pager/views/dx-pager-page-number-view.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {DxViewContracts} from '../../../internal/index';
import {PageNumberAngularVM} from '../types/index';

interface DxPagerPageNumberActions {
  selectPage: (pageNumber: number) => void;
}

@Component({
  template: '',
})
export abstract class DxPagerPageNumberViewContracts
  extends DxViewContracts<PageNumberAngularVM, DxPagerPageNumberActions> {
}

@Component({
  selector: 'dx-pager-page-number-view',
  template: `
    <div class="dx-pager-pages">
<!--      <dx-dynamic-template *ngFor="let item of viewModel.items"-->
<!--                           [template]="item.template"-->
<!--                           [data]="{-->
<!--                            viewModel: item,-->
<!--                            actions: { selectPage: actions.selectPage }-->
<!--                           }">-->
<!--      </dx-dynamic-template>-->
    </div>
  `,
  styleUrls: ['./dx-pager-page-number-view.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxPagerPageNumberViewComponent extends DxPagerPageNumberViewContracts {

}
