// packages/react/src/components/pager/views/dxPagerPageSizeView.tsx
import React from 'react';
import { PageSizeReactVM } from '../types/public/index';

interface DxPagerPageSizeViewProps {
    // TODO jQuery: Temporary wrapping for the inferno generator.
    data: {
        viewModel: PageSizeReactVM;
        selectPageSize: (pageSize: number) => void;
    }
}

const DxPagerPageSizeView = ({
    data: {
        viewModel,
        selectPageSize
    }
}: DxPagerPageSizeViewProps) => {
    return (
        <div className="dx-pager-page-size">
            {
                viewModel.items.map((item) =>
                    item.template({
                        data: {
                            item,
                            selectPageSize
                        }
                    }))
            }
        </div>
    );
};

export type { DxPagerPageSizeViewProps };
export { DxPagerPageSizeView };

// packages/angular/projects/angular/src/components/pager/views/dx-pager-page-size-view.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {DxViewContracts} from '../../../internal/index';
import {PageSizeAngularVM} from '../types/index';

interface DxPagerPageSizeActions {
  selectPageSize: (pageSize: number) => void;
}

@Component({
  template: '',
})
export abstract class DxPagerPageSizeViewContracts
  extends DxViewContracts<PageSizeAngularVM, DxPagerPageSizeActions> {
}

@Component({
  selector: 'dx-pager-page-size-view',
  template: `
    <div class="dx-pager-page-size">
<!--      <dx-dynamic-template *ngFor="let item of viewModel.items"-->
<!--                           [template]="item.template"-->
<!--                           [data]="{-->
<!--                           viewModel: item,-->
<!--                           actions: { selectPageSize: actions.selectPageSize }-->
<!--                           }">-->
<!--      </dx-dynamic-template>-->
    </div>
  `,
  styleUrls: ['./dx-pager-page-size-view.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxPagerPageSizeViewComponent extends DxPagerPageSizeViewContracts {
}
