// packages/react/src/components/pager/views/dxPagerPageNumberItemView.tsx
import React from 'react';
import { PageNumberItemTemplate, ItemReactVM } from '../types/public/index';

interface DxPagerPageNumberItemViewProps {
    // TODO jQuery: Temporary wrapping for the inferno generator.
    data: {
        item: ItemReactVM<PageNumberItemTemplate>;
        selectPage: (pageNumber: number) => void;
    }
}

const DxPagerPageNumberItemView = ({
    data: {
        item,
        selectPage
    }
}: DxPagerPageNumberItemViewProps) => {
    const clickHandler = () => selectPage(item.value);
    return (
        <div key={item.value}
            className={`dx-pager-pages__item
                        ${item.selectable ? '-selectable' : ''}
                        ${item.selected ? '-selected' : ''}`}
            onClick={clickHandler}>
            {item.label}
        </div>
    );
};

export type { DxPagerPageNumberItemViewProps };
export { DxPagerPageNumberItemView };

// packages/angular/projects/angular/src/components/pager/views/dx-pager-page-number-item-view.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {DxViewContracts} from '../../../internal/index';
import {ItemAngularVM} from '../types/index';

interface DxPagerPageNumberItemActions {
  selectPage: (pageNumber: number) => void;
}

@Component({template: ''})
export abstract class DxPagerPageNumberItemViewContracts
  extends DxViewContracts<ItemAngularVM<DxPagerPageNumberItemViewComponent>, DxPagerPageNumberItemActions> {
}

@Component({
  selector: 'dx-pager-page-number-item-view',
  template: `
    <div class="dx-pager-pages__item"
         [class.-selected]="viewModel.selected"
         [class.-selectable]="viewModel.selectable"
         (click)="actions.selectPage(viewModel.value)">
      {{ viewModel.label }}
    </div>
  `,
  styleUrls: ['./dx-pager-page-number-item-view.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxPagerPageNumberItemViewComponent extends DxPagerPageNumberItemViewContracts {
}
