// apps/demos/Demos/CardView/FieldTemplate/ReactJs/Priority.js
import React, { useMemo } from 'react';
import { priorities } from './data.js';

const PriorityComponent = ({ priorityID }) => {
  const priority = useMemo(() => priorities.find((p) => p.id === priorityID), [priorityID]);
  return (
    <div className={`task__priority task__priority--${priority?.postfix}`}>
      <div className="task__indicator" />
      <div>{priority?.text}</div>
    </div>
  );
};
export default PriorityComponent;

// apps/demos/Demos/CardView/FieldTemplate/Angular/app/priority/priority.component.ts
import { Component, Input, OnChanges } from '@angular/core';
import { Priority, Service } from '../app.service';

@Component({
  selector: 'priority',
  templateUrl: './priority.component.html',
  styleUrls: ['./priority.component.css'],
})
export class PriorityComponent implements OnChanges {
  priorities: Priority[];

  text: string;

  className: string;

  @Input() priorityID: number;

  constructor(service: Service) {
    this.priorities = service.getPriorities();
  }

  ngOnChanges(): void {
    const priority = this.priorities.find((p) => p.id === this.priorityID);
    this.text = priority.text;
    this.className = `priority priority--${priority.postfix}`;
  }
}

<div>
    <div [class]="className">
        <div class="indicator"></div>
        <div>{{ text }}</div>
    </div>
</div>
