// apps/demos/Demos/SelectBox/Overview/Vue/Item.vue
<template>
  <div class="custom-item">
    <img
      alt="Product name"
      :src="itemData.ImageSrc"
    >
    <div class="product-name">
      {{ itemData.Name }}
    </div>
  </div>
</template>
<script setup lang="ts">
withDefaults(defineProps<{
  itemData?: Record<string, any>
}>(), {
  itemData: () => ({} as Record<string, any>),
});
</script>

// apps/demos/Demos/SelectBox/Overview/React/Item.tsx
import React from 'react';

interface ItemProps {
  ImageSrc: string;
  Name: string;
}

export default function Item(data: ItemProps) {
  return (
    <div className="custom-item">
      <img
        alt="Product name"
        src={data.ImageSrc}
      />
      <div className="product-name">{data.Name}</div>
    </div>
  );
}
