// apps/demos/Demos/Charts/SimpleSparklines/Vue/RowTemplate.vue
<template>
  <tr class="rows-content">
    <th>{{ year }}</th>
    <td>
      <DxSparkline
        :data-source="oilCosts"
        :show-min-max="true"
        :value-field="year"
        class="sparkline"
        argument-field="month"
        type="line"
      >
        <DxTooltip :format="{ type: 'currency', precision: 2 }"/>
      </DxSparkline>
    </td>
    <td>
      <DxSparkline
        :data-source="goldCosts"
        :line-width="3"
        :show-min-max="true"
        :show-first-last="false"
        :value-field="year"
        class="sparkline"
        argument-field="month"
        type="spline"
        line-color="#9ab57e"
        min-color="#6babac"
        max-color="#ebdd8f"
      >
        <DxTooltip :format="{ type: 'currency', precision: 2 }"/>
      </DxSparkline>
    </td>
    <td>
      <DxSparkline
        :data-source="silverCosts"
        :point-size="6"
        :value-field="year"
        class="sparkline"
        argument-field="month"
        type="stepline"
        line-color="#e8c267"
        first-last-color="#e55253"
        point-symbol="square"
        point-color="#ebdd8f"
      >
        <DxTooltip :format="{ type: 'currency', precision: 2 }"/>
      </DxSparkline>
    </td>
  </tr>
</template>

<script setup lang="ts">
import DxSparkline, {
  DxTooltip,
} from 'devextreme-vue/sparkline';
import {
  oilCosts,
  goldCosts,
  silverCosts,
} from './data.ts';

withDefaults(defineProps<{
  year?: string
}>(), {
  year: '',
});
</script>

<style>
.rows-content td {
  font-weight: 400;
  width: 200px;
  padding: 25px 10px 5px;
  border: 1px solid #c2c2c2;
}

.rows-content tr:nth-child(2) td {
  border-top: 1px solid #c2c2c2;
}

.rows-content td:first-of-type {
  border-left: 1px solid #c2c2c2;
}

.rows-content .sparkline {
  width: 200px;
  height: 30px;
}
</style>

// apps/demos/Demos/Charts/SimpleSparklines/React/RowTemplate.tsx
import React from 'react';

import Sparkline, {
  Tooltip,
} from 'devextreme-react/sparkline';

import {
  oilCosts,
  silverCosts,
  goldCosts,
} from './data.ts';

interface RowTemplateProps {
  key: number;
  year: string;
}

export default function RowTemplate(props: RowTemplateProps) {
  return (
    <tr>
      <th>{props.year}</th>
      <td>
        <Sparkline
          dataSource={oilCosts}
          showMinMax={true}
          className="sparkline"
          argumentField="month"
          valueField={props.year}
          type="line"
        >
          <Tooltip format={{ type: 'currency', precision: 2 }} />
        </Sparkline>
      </td>
      <td>
        <Sparkline
          dataSource={goldCosts}
          lineWidth={3}
          showMinMax={true}
          showFirstLast={false}
          className="sparkline"
          argumentField="month"
          valueField={props.year}
          type="spline"
          lineColor="#9ab57e"
          minColor="#6babac"
          maxColor="#ebdd8f"
        >
          <Tooltip format={{ type: 'currency', precision: 2 }} />
        </Sparkline>
      </td>
      <td>
        <Sparkline
          dataSource={silverCosts}
          pointSize={6}
          className="sparkline"
          argumentField="month"
          valueField={props.year}
          type="stepline"
          lineColor="#e8c267"
          firstLastColor="#e55253"
          pointSymbol="square"
          pointColor="#ebdd8f"
        >
          <Tooltip format={{ type: 'currency', precision: 2 }} />
        </Sparkline>
      </td>
    </tr>
  );
}
