// packages/angular/projects/angular/src/components/radio-group/radio-group.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
} from '@angular/core';
import {
  createRadioGroupCore,
  ReadonlyProps,
  TemplateProps,
  ValueProps,
} from '@devextreme/components';
import { filter, map } from 'rxjs';
import { doIfContextExist, Inputs } from '../../internal';
import { RadioGroupService, RadioGroupValue } from '../radio-common';

export type RadioGroupInputs<T extends RadioGroupValue> =
  Inputs<ValueProps<T>, ReadonlyProps, TemplateProps>;

@Component({
  selector: 'dx-radio-group',
  template: `
    <div>
      <ng-content></ng-content>
    </div>
  `,
  providers: [RadioGroupService],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class RadioGroupComponent<T extends RadioGroupValue>
implements OnInit, RadioGroupInputs<T> {
  private inputValue?: T;

  @Input() set value(value: T) {
    this.setValue(value);
  }

  @Output() valueChange = new EventEmitter<T | undefined>();

  constructor(private radioGroupService: RadioGroupService) {
  }

  ngOnInit(): void {
    this.radioGroupService.setContext(
      createRadioGroupCore({
        value: this.inputValue,
      }, {
        value: {
          controlledMode: false,
          changeCallback: (value) => { this.valueChange.emit(value); },
        },
      }),
    );
  }

  private setValue(value: T): void {
    this.inputValue = value;

    this.radioGroupService.context$.pipe(
      doIfContextExist(),
      map(({ stateManager }) => stateManager),
      filter((stateManager) => {
        const stateValue = stateManager.getState();
        return stateValue.value !== value;
      }),
    ).subscribe((stateManager) => {
      stateManager.addUpdate({ value });
      stateManager.commitUpdates();
    });
  }
}

// packages/react/src/components/radio-group/radio-group.tsx
import {
  createRadioGroupCore, ReadonlyProps, TemplateProps, ValueProps,
} from '@devextreme/components';
import { memo, useMemo } from 'react';
import { useCallbackRef, useSecondEffect } from '../../internal/hooks';
import { Props } from '../../internal/props';
import { RadioGroupContext } from './radio-group-context';

function RadioGroupInternal<T extends RadioGroupValue>(props: RadioGroupProps<T>) {
  const controlledMode = useMemo(() => Object.hasOwnProperty.call(props, 'value'), []);
  const valueChange = useCallbackRef(props.valueChange);

  const { stateManager, viewModelManager, dispatcher } = useMemo(() => createRadioGroupCore<T>({
    value: controlledMode ? props.value : props.defaultValue,
  }, {
    value: {
      controlledMode,
      changeCallback: (value) => { valueChange.current(value); },
    },
  }), []);

  useSecondEffect(() => {
    if (controlledMode) {
      stateManager.addUpdate({ value: props.value });
    }

    stateManager.commitUpdates();
  }, [props.value]);

  return (
    <RadioGroupContext.Provider value={{ stateManager, viewModelManager, dispatcher }}>
      <div>
        {props.children}
      </div>
    </RadioGroupContext.Provider>
  );
}

export type RadioGroupValue = string | number;

export type RadioGroupProps<T> =
  React.PropsWithChildren<Props<ValueProps<T>, ReadonlyProps, TemplateProps>>;

export const RadioGroup = memo(RadioGroupInternal) as typeof RadioGroupInternal;
