// apps/demos/Demos/Stepper/FormIntegration/ReactJs/RoomMealPlanForm.js
import React, { memo } from 'react';
import 'devextreme-react/select-box';
import { Form, SimpleItem } from 'devextreme-react/form';
import { mealPlans, roomTypes } from './data.js';

const RoomMealPlanForm = memo(({ formData, validationGroup }) => (
  <>
    <p>
      Review room types that can accommodate your group size and make your selection. You can also
      choose a meal plan, whether it's breakfast only or full board.
    </p>

    <Form
      formData={formData}
      validationGroup={validationGroup}
      colCount={2}
    >
      <SimpleItem
        dataField="roomType"
        isRequired
        editorType="dxSelectBox"
        label={{ text: 'Room Type', location: 'top' }}
        editorOptions={{
          items: roomTypes,
          elementAttr: { id: 'roomType' },
        }}
      />
      <SimpleItem
        dataField="mealPlan"
        isRequired
        editorType="dxSelectBox"
        label={{ text: 'Meal Plan', location: 'top' }}
        editorOptions={{
          items: mealPlans,
          elementAttr: { id: 'mealPlan' },
        }}
      />
    </Form>
  </>
));
RoomMealPlanForm.displayName = 'RoomMealPlanForm';
export default RoomMealPlanForm;

// apps/demos/Demos/Stepper/FormIntegration/Angular/app/room-meal-plan-form/room-meal-plan-form.component.ts
import { Component, Input } from '@angular/core';
import { DxFormTypes } from 'devextreme-angular/ui/form';
import { DxSelectBoxTypes } from 'devextreme-angular/ui/select-box';
import type { BookingFormData } from '../app.types';

let modulePrefix = '';
// @ts-ignore
if (window && window.config?.packageConfigPaths) {
  modulePrefix = '/app';
}

@Component({
  selector: 'room-meal-plan-form',
  templateUrl: `.${modulePrefix}/room-meal-plan-form/room-meal-plan-form.component.html`,
})
export class RoomMealPlanFormComponent {
  @Input() formData: BookingFormData;

  @Input() validationGroup: string;

  roomLabelOptions: DxFormTypes.SimpleItem["label"] = {
    text: 'Room Type',
    location: 'top',
  };

  mealLabelOptions: DxFormTypes.SimpleItem["label"] = {
    text: 'Meal Plan',
    location: 'top',
  };

  roomTypes = ['Single', 'Double', 'Suite'];

  mealPlans = ['Bed & Breakfast', 'Half Board', 'Full Board', 'All-Inclusive'];

  mealSelectBoxOptions: DxSelectBoxTypes.Properties = {
    items: this.mealPlans,
    elementAttr: { id: 'mealPlan' },
  };

  roomSelectBoxOptions: DxSelectBoxTypes.Properties = {
    items: this.roomTypes,
    elementAttr: { id: 'roomType' },
  }
}

<p>
  Review room types that can accommodate your group size and make your
  selection. You can also choose a meal plan, whether it's breakfast only or
  full board.
</p>
<dx-form
  [(formData)]="formData"
  [validationGroup]="validationGroup"
  [colCount]="2"
>
  <dxi-item
    [isRequired]="true"
    dataField="roomType"
    editorType="dxSelectBox"
    [editorOptions]="roomSelectBoxOptions"
    [label]="roomLabelOptions"
  >
    <dxi-validation-rule type="required"></dxi-validation-rule>
  </dxi-item>

  <dxi-item
    [isRequired]="true"
    dataField="mealPlan"
    editorType="dxSelectBox"
    [editorOptions]="mealSelectBoxOptions"
    [label]="mealLabelOptions"
  >
    <dxi-validation-rule type="required"></dxi-validation-rule>
  </dxi-item>
</dx-form>
