// apps/demos/Demos/FilterBuilder/Customization/ReactJs/EditorComponent.js
import React, { useCallback } from 'react';
import TagBox from 'devextreme-react/tag-box';
import { categories, categoryLabel } from './data.js';

export const EditorComponent = (props) => {
  const onValueChanged = useCallback(
    (e) => {
      props.data.setValue(e.value && e.value.length ? e.value : null);
    },
    [props.data],
  );
  return (
    <TagBox
      inputAttr={categoryLabel}
      defaultValue={props.data.value}
      items={categories}
      onValueChanged={onValueChanged}
      width="auto"
    />
  );
};

// Demos/FilterBuilder/Customization/Vue/EditorComponent.vue
<template>
  <DxTagBox
    :value="conditionInfo.value"
    :items="categories"
    width="auto"
    @value-changed="onValueChanged"
  />
</template>

<script>
import DxTagBox from 'devextreme-vue/tag-box';
import { categories } from './data.js';

export default {
  components: {
    DxTagBox,
  },
  props: {
    conditionInfo: {
      type: Object,
      default: () => {},
    },
  },
  data() {
    return {
      categories,
    };
  },
  methods: {
    onValueChanged(e) {
      this.conditionInfo.setValue(e.value && e.value.length ? e.value : null);
    },
  },
};
</script>
