// Demos/Charts/SignalRService/Vue/TooltipTemplate.vue
<template>
  <div class="tooltip-template">
    <div>{{ pointInfo.argumentText }}</div>
    <div><span>Open: </span>
      {{ formatCurrency(prices.openValue, "USD") }}
    </div>
    <div><span>High: </span>
      {{ formatCurrency(prices.highValue, "USD") }}
    </div>
    <div><span>Low: </span>
      {{ formatCurrency(prices.lowValue, "USD") }}
    </div>
    <div><span>Close: </span>
      {{ formatCurrency(prices.closeValue, "USD") }}
    </div>
    <div><span>Volume: </span>
      {{ formatNumber(volume.value, { maximumFractionDigits: 0 }) }}
    </div>
  </div>
</template>
<script>

export default {
  props: {
    pointInfo: {
      type: Object,
      default: () => {},
    },
  },
  data() {
    return {
      volume: this.pointInfo.points.filter((point) => point.seriesName === 'Volume')[0],
      prices: this.pointInfo.points.filter((point) => point.seriesName !== 'Volume')[0],
    };
  },
  methods: {
    formatCurrency: new Intl.NumberFormat('en-US',
      { style: 'currency', currency: 'USD', minimumFractionDigits: 0 }).format,

    formatNumber: new Intl.NumberFormat('en-US', {
      minimumFractionDigits: 0,
    }).format,
  },
};
</script>
<style>
.tooltip-template span {
  font-weight: 500;
}
</style>

// apps/demos/Demos/Charts/SignalRService/React/TooltipTemplate.tsx
import React from 'react';

const formatCurrency = new Intl.NumberFormat('en-US',
  { style: 'currency', currency: 'USD', minimumFractionDigits: 0 }).format;

const formatNumber = new Intl.NumberFormat('en-US', {
  minimumFractionDigits: 0,
}).format;

export default function TooltipTemplate(pointInfo: any) {
  const volume = pointInfo.points.filter((point: { seriesName: string; }): boolean => point.seriesName === 'Volume')[0];
  const prices = pointInfo.points.filter((point: { seriesName: string; }): boolean => point.seriesName !== 'Volume')[0];

  return (
    <div className="tooltip-template">
      <div>{ pointInfo.argumentText }</div>
      <div><span>Open: </span>
        { formatCurrency(prices.openValue) }
      </div>
      <div><span>High: </span>
        { formatCurrency(prices.highValue) }
      </div>
      <div><span>Low: </span>
        { formatCurrency(prices.lowValue) }
      </div>
      <div><span>Close: </span>
        { formatCurrency(prices.closeValue) }
      </div>
      <div><span>Volume: </span>
        { formatNumber(volume.value) }
      </div>
    </div>
  );
}
