// apps/demos/Demos/VectorMap/Overview/Vue/PieChart.vue
<template>
  <DxPieChart
    :data-source="data"
    :animation="false"
  >
    <DxSeries
      argument-field="name"
      value-field="value"
    >
      <DxLabel
        :visible="true"
        :customize-text="customizeText"
      >
        <DxConnector
          :visible="true"
          :width="1"
        />
      </DxLabel>
    </DxSeries>
    <DxLegend :visible="false"/>
  </DxPieChart>
</template>
<script setup lang="ts">
import DxPieChart, {
  DxSeries,
  DxLabel,
  DxLegend,
  DxConnector,
} from 'devextreme-vue/pie-chart';

withDefaults(defineProps<{
  data?: { name: string, value: unknown }[]
}>(), {
  data: () => [],
});

const customizeText = (pointInfo) => `${pointInfo.argument[0].toUpperCase()}${pointInfo.argument.slice(1)}: $${pointInfo.value}M`;
</script>

// Demos/VectorMap/Overview/React/PieChartComponent.js
import React from 'react';
import PieChart, {
  Series,
  Label,
  Legend,
  Connector,
} from 'devextreme-react/pie-chart';

function customizeText(pointInfo) {
  return `${pointInfo.argument[0].toUpperCase()}${
    pointInfo.argument.slice(1)
  }: $${pointInfo.value}M`;
}

function PieChartComponent({ data = [] }) {
  return (
    <PieChart id="gdp-sectors"
      dataSource={data}
      animation={false}
    >
      <Series
        argumentField="name"
        valueField="value">
        <Label
          visible={true}
          customizeText={customizeText}
        >
          <Connector
            visible={true}
            width={1}
          ></Connector>
        </Label>
      </Series>
      <Legend visible={false}></Legend>
    </PieChart>
  );
}

export default PieChartComponent;
