// Demos/Drawer/TopOrBottomPosition/Vue/NavigationList.vue
<template>
  <div>
    <DxList
      :data-source="navigation"
      :active-state-enabled="false"
      :hover-state-enabled="false"
      :focus-state-enabled="false"
      class="panel-list dx-theme-accent-as-background-color"
    />
  </div>
</template>
<script>

import { DxList } from 'devextreme-vue/list';
import { navigation } from './data.js';

export default {
  components: {
    DxList
  },
  data() {
    return {
      navigation
    };
  }
};
</script>

// Demos/Drawer/TopOrBottomPosition/React/NavigationList.js
import React from 'react';

import List from 'devextreme-react/list.js';
import { navigation } from './data.js';

function NavigationList() {
  return (
    <div className="list">
      <List
        dataSource={navigation}
        className="panel-list dx-theme-accent-as-background-color"
        height={200} />
    </div>
  );
}

export default NavigationList;
