// apps/demos/Demos/TreeList/AIColumns/Vue/Name.vue
<template>
  <div class="name__wrapper">
    <div class="name__img-wrapper">
      <img
        :src="`../../../../images/employees/new/${firstName} ${lastName}.jpg`"
        :alt="`${firstName} ${lastName}`"
      >
    </div>
    <div class="name__text-wrapper">
      <div>{{ firstName }}</div>
      <div>{{ lastName }}</div>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  firstName: string;
  lastName: string;
}>();
</script>

<style scoped>
.name__wrapper {
  display: flex;
  align-items: center;
  gap: 8px;
}

.name__img-wrapper {
  width: 40px;
  height: 40px;
  border: var(--dx-border-width) solid var(--dx-color-border);
  border-radius: 50%;
  cursor: pointer;
}

.name__img-wrapper img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  object-position: center;
  border-radius: 50%;
}

.name__text-wrapper {
  width: calc(100% - 48px);
}
</style>

// apps/demos/Demos/TreeList/AIColumns/ReactJs/Name.js
import React from 'react';

export default function Name(props) {
  const { First_Name, Last_Name } = props.data;
  return (
    <div className="name__wrapper">
      <div className="name__img-wrapper">
        <img
          src={`../../../../images/employees/new/${First_Name} ${Last_Name}.jpg`}
          alt={`${First_Name} ${Last_Name}`}
        />
      </div>
      <div className="name__text-wrapper">
        <div>{First_Name}</div>
        <div>{Last_Name}</div>
      </div>
    </div>
  );
}
