// Demos/Drawer/LeftOrRightPosition/ReactJs/NavigationList.js
import React from 'react';
import List from 'devextreme-react/list';
import { navigation } from './data.js';

function NavigationList() {
  return (
    <div
      className="list"
      style={{ width: '200px' }}
    >
      <List
        dataSource={navigation}
        hoverStateEnabled={false}
        activeStateEnabled={false}
        focusStateEnabled={false}
        className="panel-list dx-theme-typography-background-color"
      />
    </div>
  );
}
export default NavigationList;

// Demos/Drawer/LeftOrRightPosition/Vue/NavigationList.vue
<template>
  <div style="width: 200px;">
    <DxList
      :data-source="navigation"
      :active-state-enabled="false"
      :hover-state-enabled="false"
      :focus-state-enabled="false"
      class="panel-list dx-theme-typography-background-color"
    />
  </div>
</template>
<script setup lang="ts">
import { DxList } from 'devextreme-vue/list';
import { navigation } from './data.js';
</script>
