// apps/demos/Demos/List/WebAPI/Vue/ProductInfo.vue
<template>
  <div>
    <div>{{ item.CategoryName }}</div>
    <div>{{ item.ProductName }}</div>
    <b class="price">{{ currency(item.UnitPrice) }}</b>
  </div>
</template>
<script setup lang="ts">
type Item = { CategoryName: string, ProductName: string, UnitPrice: number };

withDefaults(defineProps<{
  item?: Item
}>(), {
  item: () => ({} as Item),
});

function currency(data: number) {
  return currencyFormatter.format(data);
}
const currencyFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
});
</script>

// Demos/List/WebAPI/React/ProductInfo.js
import React from 'react';

const currencyFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
});

export default function ProductInfo(item) {
  return (
    <React.Fragment>
      <div>{item.CategoryName}</div>
      <div>{item.ProductName}</div>
      <b className="price">{currencyFormatter.format(item.UnitPrice)}</b>
    </React.Fragment>
  );
}
