// apps/demos/Demos/DataGrid/CellCustomization/Vue/ChartCell.vue
<template>
  <div class="chart-cell">
    <DxSparkline
      :data-source="dayClose"
      :show-min-max="true"
      :point-size="6"
      argument-field="date"
      value-field="close"
      type="line"
      min-color="#f00"
      max-color="#2ab71b"
    >
      <DxSize
        :width="290"
        :height="40"
      />
      <DxTooltip :enabled="false"/>
    </DxSparkline>
  </div>
</template>
<script setup lang="ts">
import {
  DxSparkline,
  DxSize,
  DxTooltip,
} from 'devextreme-vue/sparkline';

import { DayClose } from './data.ts';

defineProps<{
  dayClose: DayClose[]
}>();
</script>

// Demos/DataGrid/CellCustomization/React/ChartCell.js
import React from 'react';
import Sparkline, { Size, Tooltip } from 'devextreme-react/sparkline';

const ChartCell = (cellData) => (
  <div className="chart-cell">
    <Sparkline
      dataSource={cellData.data.dayClose}
      argumentField="date"
      valueField="close"
      type="line"
      showMinMax={true}
      minColor="#f00"
      maxColor="#2ab71b"
      pointSize={6}>
      <Size width={290} height={40} />
      <Tooltip enabled={false} />
    </Sparkline>
  </div>
);

export default ChartCell;
