// Demos/DataGrid/CellCustomization/Vue/DiffCell.vue
<template>
  <div :class="className(cellData)">
    <div class="current-value">{{ formatCurrency(cellData) }}</div>
    <div class="diff">{{ fixed(abs(cellData), 2) }}</div>
  </div>
</template>
<script setup lang="ts">
import { formatNumber } from 'devextreme/localization';

withDefaults(defineProps<{
  cellData?: object
}>(), {
  cellData: () => {},
});

function className(value) {
  return gridCellData(value).diff > 0 ? 'inc' : 'dec';
}
function formatCurrency(value) {
  return formatNumber(gridCellData(value).value, { type: 'currency', currency: 'USD', precision: 2 });
}
function abs(value) {
  return Math.abs(gridCellData(value).diff);
}
function fixed(value, precision) {
  return value.toFixed(precision);
}
const gridCellData = function(value) {
  return value.data[value.column.caption.toLowerCase()];
};
</script>

// Demos/DataGrid/CellCustomization/React/DiffCell.js
import React from 'react';
import 'devextreme/localization/globalize/currency';
import { formatNumber } from 'devextreme/localization';

function gridCellData(gridData) {
  return gridData.data[gridData.column.caption.toLowerCase()];
}

export default function DiffCell(cellData) {
  return (
    <div className={gridCellData(cellData).diff > 0 ? 'inc' : 'dec'}>
      <div className="current-value">{formatNumber(gridCellData(cellData).value, { type: 'currency', currency: 'USD', precision: 2 })}</div>
      <div className="diff">{Math.abs(gridCellData(cellData).diff).toFixed(2)}</div>
    </div>
  );
}
