// packages/angular/projects/angular/src/components/pager/views/dx-pager-page-size-item-view.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {DxViewContracts} from '../../../internal/index';
import {ItemAngularVM} from '../types/index';

interface DxPagerPageSizeItemActions {
  selectPageSize: (pageSize: number) => void;
}

@Component({
  template: '',
})
export abstract class DxPagerPageSizeItemViewContracts
  extends DxViewContracts<ItemAngularVM<DxPagerPageSizeItemViewComponent>, DxPagerPageSizeItemActions> {
}

@Component({
  selector: 'dx-pager-page-size-item-view',
  template: `
    <div class="dx-pager-page-size__item"
         [class.-selected]="viewModel.selected"
         (click)="actions.selectPageSize(viewModel.value)">
      {{ viewModel.label }}
    </div>
  `,
  styleUrls: ['./dx-pager-page-size-item-view.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxPagerPageSizeItemViewComponent extends DxPagerPageSizeItemViewContracts {
}

// packages/react/src/components/pager/views/dxPagerPageSizeItemView.tsx
import React from 'react';
import { PageSizeItemTemplate, ItemReactVM } from '../types/public/index';

interface DxPagerPageSizeItemViewProps {
    // TODO jQuery: Temporary wrapping for the inferno generator.
    data: {
        item: ItemReactVM<PageSizeItemTemplate>;
        selectPageSize: (pageSize: number) => void;
    }
}

const DxPagerPageSizeItemView = ({
    data: {
        item,
        selectPageSize
    }
}: DxPagerPageSizeItemViewProps) => {
    const clickHandler = () => {
        selectPageSize(item.value);
    };
    return (
        <div key={item.value}
            className={`dx-pager-page-size__item ${item.selected ? '-selected' : ''}`}
            onClick={clickHandler}>
            {item.label}
        </div>
    );
};

export type { DxPagerPageSizeItemViewProps };
export { DxPagerPageSizeItemView };
