// apps/demos/Demos/TagBox/Overview/Vue/Item.vue
<template>
  <div class="custom-item">
    <img
      :src="itemData.ImageSrc"
      :alt="`${itemData.Name}. Picture`"
    >
    <div class="product-name">
      {{ itemData.Name }}
    </div>
  </div>
</template>
<script setup lang="ts">
withDefaults(defineProps<{
  itemData?: { [key: string]: string }
}>(), {
  itemData: () => ({ Name: '' }),
});
</script>

// apps/demos/Demos/Lookup/Templates/React/Item.tsx
import React from 'react';
import type { Employee } from './types.ts';

export default function Item({
  Picture, Prefix, FirstName, LastName,
}: Employee) {
  return (
    <div className="custom-item">
      <img alt={FirstName} src={Picture} /><div>{`${Prefix} ${FirstName} ${LastName}`}</div>
    </div>
  );
}
