// apps/demos/Demos/DataGrid/CustomEditors/Vue/EmployeeDropDownBoxComponent.vue
<template>
  <DxDropDownBox
    ref="dropDownBoxRef"
    :drop-down-options="dropDownOptions"
    :input-attr="{ 'aria-label': 'Owner' }"
    :data-source="dataSource"
    v-model:value="currentValue"
    display-expr="FullName"
    value-expr="ID"
    content-template="contentTemplate"
  >
    <template #contentTemplate="{}">
      <DxDataGrid
        :data-source="dataSource"
        :remote-operations="true"
        :height="250"
        :selected-row-keys="getSelectedRowKeys(currentValue)"
        :hover-state-enabled="true"
        :on-context-menu-preparing="onContextMenuPreparing"
        :on-selection-changed="onSelectionChanged"
        :focused-row-enabled="true"
        :focused-row-key="currentValue"
      >
        <DxColumn data-field="FullName"/>
        <DxColumn data-field="Title"/>
        <DxColumn data-field="Department"/>
        <DxPaging
          :enabled="true"
          :page-size="10"
        />
        <DxScrolling mode="virtual"/>
        <DxSelection mode="single"/>
      </DxDataGrid>
    </template>
  </DxDropDownBox>
</template>
<script setup lang="ts">
import { ref } from 'vue';
import {
  DxDataGrid,
  DxPaging,
  DxSelection,
  DxScrolling,
  DxColumn,
  type DxDataGridTypes,
} from 'devextreme-vue/data-grid';
import DxDropDownBox, { type DxDropDownBoxTypes } from 'devextreme-vue/drop-down-box';
import { CustomStore } from 'devextreme-vue/common/data';

const props = defineProps<{
  value: number,
  onValueChanged(value: number): void,
  dataSource: CustomStore,
}>();

const currentValue = ref(props.value);
const dropDownBoxRef = ref<DxDropDownBox | null>(null);
const dropDownOptions: DxDropDownBoxTypes.Properties['dropDownOptions'] = { width: 500 };

function getSelectedRowKeys<T>(value: T | null): T[] {
  return value !== null && value !== undefined ? [value] : [];
}

const onContextMenuPreparing = (e: DxDataGridTypes.ContextMenuPreparingEvent) => {
  e.items = [];
};
const onSelectionChanged = (e: DxDataGridTypes.SelectionChangedEvent) => {
  currentValue.value = e.selectedRowKeys[0];

  props.onValueChanged(currentValue.value);

  if (e.selectedRowKeys.length > 0) {
    dropDownBoxRef.value!.instance!.close();
  }
};
</script>

// apps/demos/Demos/DataGrid/CustomEditors/React/EmployeeDropDownBoxComponent.tsx
import React, { useCallback, useState } from 'react';
import DataGrid, {
  Column,
  DataGridTypes,
  Paging,
  Scrolling,
  Selection,
} from 'devextreme-react/data-grid';
import DropDownBox, { DropDownBoxTypes } from 'devextreme-react/drop-down-box';

const dropDownOptions = { width: 500 };
const ownerLabel = { 'aria-label': 'Owner' };

const EmployeeDropDownBoxComponent = (props) => {
  const [selectedRowKeys, setSelectedRowKeys] = useState([props.data.value]);
  const [isDropDownOpened, setDropDownOpened] = useState(false);

  const boxOptionChanged = useCallback((e: DropDownBoxTypes.OptionChangedEvent) => {
    if (e.name === 'opened') {
      setDropDownOpened(e.value);
    }
  }, []);

  const contentRender = useCallback(() => {
    const onContextMenuPreparing = (event: DataGridTypes.ContextMenuPreparingEvent) => {
      event.items = [];
    };
    const onSelectionChanged = (args: DataGridTypes.SelectionChangedEvent) => {
      setSelectedRowKeys(args.selectedRowKeys);
      setDropDownOpened(false);

      props.data.setValue(args.selectedRowKeys[0]);
    };

    return (
      <DataGrid
        dataSource={props.data.column.lookup.dataSource}
        remoteOperations={true}
        height={250}
        selectedRowKeys={selectedRowKeys}
        hoverStateEnabled={true}
        onContextMenuPreparing={onContextMenuPreparing}
        onSelectionChanged={onSelectionChanged}
        focusedRowEnabled={true}
        defaultFocusedRowKey={selectedRowKeys[0]}
      >
        <Column dataField="FullName" />
        <Column dataField="Title" />
        <Column dataField="Department" />
        <Paging enabled={true} defaultPageSize={10} />
        <Scrolling mode="virtual" />
        <Selection mode="single" />
      </DataGrid>
    );
  }, [props.data, selectedRowKeys]);

  return (
    <DropDownBox
      onOptionChanged={boxOptionChanged}
      opened={isDropDownOpened}
      dropDownOptions={dropDownOptions}
      dataSource={props.data.column.lookup.dataSource}
      value={selectedRowKeys[0]}
      displayExpr="FullName"
      valueExpr="ID"
      inputAttr={ownerLabel}
      contentRender={contentRender}>
    </DropDownBox>
  );
};

export default EmployeeDropDownBoxComponent;
