// Demos/DataGrid/CustomEditors/Vue/EmployeeTagBoxComponent.vue
<template>
  <DxTagBox
    :data-source="dataSource"
    v-model:value="currentValue"
    :show-selection-controls="true"
    :input-attr="{ 'aria-label': 'Name' }"
    :max-displayed-tags="3"
    :show-multi-tag-only="false"
    :on-value-changed="onValueChanged"
    :on-selection-changed="onSelectionChanged"
    :search-enabled="true"
    value-expr="ID"
    display-expr="FullName"
    apply-value-mode="useButtons"
  />
</template>
<script setup lang="ts">
import { ref } from 'vue';
import { DxDataGridTypes } from 'devextreme-vue/data-grid';
import DxTagBox, { DxTagBoxTypes } from 'devextreme-vue/tag-box';
import CustomStore from 'devextreme/data/custom_store';

const props = defineProps<{
  cellInfo: DxDataGridTypes.ColumnEditCellTemplateData,
  dataSource: CustomStore,
  dataGridComponent: DxDataGridTypes.DataGrid,
}>();

const currentValue = ref(props.cellInfo.value);

const onSelectionChanged = () => {
  props.dataGridComponent.updateDimensions();
};

const onValueChanged = (e: DxTagBoxTypes.ValueChangedEvent) => {
  props.cellInfo.setValue(e.value);
};
</script>

// apps/demos/Demos/DataGrid/CustomEditors/React/EmployeeTagBoxComponent.tsx
import React, { useCallback } from 'react';

import TagBox, { type TagBoxTypes } from 'devextreme-react/tag-box';
import type { DataGridTypes } from 'devextreme-react/data-grid';

const nameLabel = { 'aria-label': 'Name' };

const EmployeeTagBoxComponent = (props: DataGridTypes.ColumnCellTemplateData) => {
  const onValueChanged = useCallback((e: TagBoxTypes.ValueChangedEvent) => {
    props.data.setValue(e.value);
  }, [props]);

  const onSelectionChanged = useCallback(() => {
    props.data.component.updateDimensions();
  }, [props]);

  return (
    <TagBox
      dataSource={props.data.column.lookup.dataSource}
      defaultValue={props.data.value}
      valueExpr="ID"
      displayExpr="FullName"
      showSelectionControls={true}
      maxDisplayedTags={3}
      inputAttr={nameLabel}
      showMultiTagOnly={false}
      applyValueMode="useButtons"
      searchEnabled={true}
      onValueChanged={onValueChanged}
      onSelectionChanged={onSelectionChanged} />
  );
};

export default EmployeeTagBoxComponent;
