// apps/demos/Demos/Stepper/FormIntegration/Angular/app/additional-form/additional-form.component.ts
import { Component, Input } from '@angular/core';
import { DxFormModule } from 'devextreme-angular';
import { type DxFormTypes } from 'devextreme-angular/ui/form';
import { type DxTextAreaTypes } from 'devextreme-angular/ui/text-area';
import 'devextreme/ui/text_area';
import type { BookingFormData } from '../app.types';

@Component({
  selector: 'additional-form',
  templateUrl: './additional-form.component.html',
  imports: [
    DxFormModule,
  ],
})
export class AdditionalFormComponent {
  @Input() formData: BookingFormData;

  textAreaOptions: DxTextAreaTypes.Properties = {
    height: 160,
    elementAttr: { id: 'additionalRequest' },
  };

  labelOptions: DxFormTypes.SimpleItem['label'] = {
    visible: false,
  };
}

<div> Please let us know if you have any other requests. </div>
<dx-form [(formData)]="formData">
  <dxi-form-item
    dataField="additionalRequest"
    editorType="dxTextArea"
    [editorOptions]="textAreaOptions"
    [label]="labelOptions"
  >
  </dxi-form-item>
</dx-form>

// apps/demos/Demos/Stepper/FormIntegration/ReactJs/AdditionalForm.js
import React, { memo } from 'react';
import 'devextreme-react/text-area';
import { Form, SimpleItem } from 'devextreme-react/form';

const AdditionalForm = memo(({ formData }) => (
  <>
    <div>Please let us know if you have any other requests.</div>
    <Form formData={formData}>
      <SimpleItem
        dataField="additionalRequest"
        editorType="dxTextArea"
        editorOptions={{
          height: 160,
          elementAttr: { id: 'additionalRequest' },
        }}
        label={{ visible: false }}
      ></SimpleItem>
    </Form>
  </>
));
AdditionalForm.displayName = 'AdditionalForm';
export default AdditionalForm;
