// apps/demos/Demos/DataGrid/CellCustomization/Vue/DiffCell.vue
<template>
  <div :class="className">
    <div class="current-value">{{ currencyFormat }}</div>
    <div class="diff">{{ difference }}</div>
  </div>
</template>
<script setup lang="ts">
import { formatNumber } from 'devextreme/common/core/localization';
import { DxDataGridTypes } from 'devextreme-vue/data-grid';

import { WeekData, DiffValueProperties } from './data.ts';

const props = defineProps<{
  column: DxDataGridTypes.Column,
  rowData: WeekData,
}>();

const getCellData = () => {
  const property = props.column.caption!.toLowerCase() as DiffValueProperties;

  return props.rowData![property];
};

const cellData = getCellData();

const className = cellData.diff > 0 ? 'inc' : 'dec';
const currencyFormat = formatNumber(cellData.value, { type: 'currency', currency: 'USD', precision: 2 });
const difference = Math.abs(cellData.diff).toFixed(2);
</script>

// apps/demos/Demos/DataGrid/Cell/ReactJs/DiffCell.js
import React from 'react';
import { formatNumber } from 'devextreme-react/common/core/localization';

const getGridCellData = (gridData) => gridData.data[gridData.column.caption.toLowerCase()];
const DiffCell = (cellData) => {
  const gridCellData = getGridCellData(cellData);
  return (
    <div className={gridCellData.diff > 0 ? 'inc' : 'dec'}>
      <div className="current-value">
        {formatNumber(gridCellData.value, { type: 'currency', currency: 'USD', precision: 2 })}
      </div>
      <div className="diff">{Math.abs(gridCellData.diff).toFixed(2)}</div>
    </div>
  );
};
export default DiffCell;
