// apps/demos/Demos/CardView/FieldTemplate/ReactJs/Employee.js
import React, { useMemo } from 'react';
import { employees } from './data.js';

const EmployeeComponent = ({ employeeID }) => {
  const employee = useMemo(() => employees.find((e) => e.ID === employeeID), [employeeID]);
  return <button className="task__link-button">{employee.Name}</button>;
};
export default EmployeeComponent;

// apps/demos/Demos/CardView/FieldTemplate/Angular/app/employee/employee.component.ts
import { Component, Input } from '@angular/core';
import { Employee, EmployeeService } from '../employee.service';

let modulePrefix = '';
// @ts-ignore
if (window && window.config?.packageConfigPaths) {
  modulePrefix = '/app';
}

@Component({
  selector: 'employee',
  templateUrl: `.${modulePrefix}/employee/employee.component.html`,
})
export class EmployeeComponent {
  employees: Employee[];
  text: string;

  @Input() employeeID: number;

  constructor(service: EmployeeService) {
    this.employees = service.getEmployees();
  }

  ngOnChanges(): void {
    const employee = this.employees.find(e => e.ID === this.employeeID);
    this.text = employee.Name;
  }
}

<button>{{ text }}</button>
