// packages/react/src/components/slideToggle/containers/dxSlideToggleContainer.tsx
import React, { useCallback, useContext } from 'react';
import { SLIDE_TOGGLE_GENERAL_SELECTOR } from '@devexpress/core/slideToggle';

import './dxSlideToggleContainer.scss';
import { useSelector } from '../../../internal/index';
import { SlideToggleContext } from '../dxSlideToggleContext';
import { IndicatorViewTemplate, TextViewTemplate } from '../types/public/index';

const DxSlideToggleContainer = React.memo(() => {
    const [store, callbacks] = useContext(SlideToggleContext)!;
    const viewModel = useSelector(store, SLIDE_TOGGLE_GENERAL_SELECTOR);

    const updateValueCallback = useCallback(
        () => callbacks.valueChange(!viewModel.model.value),
        [viewModel.model.value]);

    // TODO: Think about how to save a template types without casting from the unknown.
    const indicatorView = viewModel.template.indicatorView as IndicatorViewTemplate;
    const textView = viewModel.template.textView as TextViewTemplate;

    return (
        <div
            className={`dx-slide-toggle ${viewModel.config.textPosition === 'left' ? '-left' : '-right'}`}
            onClick={updateValueCallback}>
            {
                indicatorView({
                    data: {
                        value: viewModel.model.value,
                        textPosition: viewModel.config.textPosition
                    }
                })
            }
            {
                textView({ data: { text: viewModel.config.text } })
            }
        </div>
    );
});

export { DxSlideToggleContainer };

// packages/angular/projects/angular/src/components/slideToggle/containers/dx-slide-toggle-container.component.ts
import { ChangeDetectionStrategy, Component, Inject, OnInit } from '@angular/core';
import { useSelector } from '../../../internal/index';
import { SLIDE_TOGGLE_GENERAL_SELECTOR } from '@devexpress/core/src/components/slideToggle';
import { SlideToggleState } from '@devexpress/core/src/components/slideToggle';
import { Observable } from 'rxjs';
import { SLIDE_TOGGLE_CONTEXT_TOKEN, SlideToggleCallbacks, type SlideToggleContext } from '../context';


@Component({
  selector: 'dx-slide-toggle-container',
  template: `
    <ng-container *ngIf="viewModel$ && callbacks">
      <div *ngIf="viewModel$ | async as viewModel"
           class="dx-slide-toggle"
           [class.-left]="viewModel.config.textPosition === 'left'"
           [class.-right]="viewModel.config.textPosition === 'right'"
           (click)="callbacks.valueChange(!viewModel.model.value)">
<!--        <dx-dynamic-template [template]="viewModel.template.indicatorView"-->
<!--                             [data]="{viewModel}">-->
<!--        </dx-dynamic-template>-->
<!--        <dx-dynamic-template [template]="viewModel.template.textView"-->
<!--                             [data]="{viewModel}">-->
<!--        </dx-dynamic-template>-->
      </div>
    </ng-container>
  `,
  styleUrls: ['./dx-slide-toggle-container.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxSlideToggleContainerComponent implements OnInit {
  callbacks?: SlideToggleCallbacks;
  viewModel$?: Observable<SlideToggleState>;

  constructor(@Inject(SLIDE_TOGGLE_CONTEXT_TOKEN) private contextContainer: SlideToggleContext) {
  }

  ngOnInit(): void {
    const [store, callbacks] = this.contextContainer.context!;
    this.callbacks = callbacks;
    this.viewModel$ = useSelector<SlideToggleState, SlideToggleState>(store, SLIDE_TOGGLE_GENERAL_SELECTOR);
  }
}
