// Demos/Accordion/Overview/Vue/CustomItem.vue
<template>
  <div>
    <div>
      <p>
        <b>{{ itemData.City }}</b>
        (<span>{{ itemData.State }}</span>)
      </p>
      <p>
        <span>{{ itemData.Zipcode }}</span>
        <span>{{ itemData.Address }}</span>
      </p>
    </div>
    <div>
      <p>
        Phone: <b>{{ itemData.Phone }}</b>
      </p>
      <p>
        Fax: <b>{{ itemData.Fax }}</b>
      </p>
      <p>
        Website:
        <a
          :href="itemData.Website"
          target="_blank"
        >
          {{ itemData.Website }}
        </a>
      </p>
    </div>
  </div>
</template>
<script>
export default {
  props: {
    itemData: {
      type: Object,
      default: () => {}
    }
  }
};
</script>

// demos/Demos/Accordion/Overview/React/CustomItem.tsx
import React from 'react';

export default function CustomItem(data) {
  return (
    <div>
      <div>
        <p>
          <b>{data.City} </b>
          (<span>{data.State}</span>)
        </p>
        <p>
          <span>{data.Zipcode} </span>
          <span>{data.Address}</span>
        </p>
      </div>
      <div>
        <p>
          Phone: <b>{data.Phone}</b>
        </p>
        <p>
          Fax: <b>{data.Fax}</b>
        </p>
        <p>
          Website: <a href={data.Website} target="_blank">
            {data.Website}
          </a>
        </p>
      </div>
    </div>
  );
}
