// apps/demos/Demos/Accordion/Overview/React/CustomItem.tsx
import React from 'react';
import type { Company } from './types.ts';

export default function CustomItem(company: Company) {
  const {
    Address,
    City,
    State,
    Zipcode,
    Phone,
    Fax,
    Website,
  } = company;

  return (
    <div>
      <div>
        <p>
          <b>{City} </b>
          (<span>{State}</span>)
        </p>
        <p>
          <span>{Zipcode} </span>
          <span>{Address}</span>
        </p>
      </div>
      <div>
        <p>
          Phone: <b>{Phone}</b>
        </p>
        <p>
          Fax: <b>{Fax}</b>
        </p>
        <p>
          Website: <a href={Website} target="_blank">
            {Website}
          </a>
        </p>
      </div>
    </div>
  );
}

// Demos/Accordion/Overview/Vue/CustomItem.vue
<template>
  <div>
    <div>
      <p>
        <b>{{ itemData.City }}</b>
        (<span>{{ itemData.State }}</span>)
      </p>
      <p>
        <span>{{ itemData.Zipcode }}</span>
        <span>{{ itemData.Address }}</span>
      </p>
    </div>
    <div>
      <p>
        Phone: <b>{{ itemData.Phone }}</b>
      </p>
      <p>
        Fax: <b>{{ itemData.Fax }}</b>
      </p>
      <p>
        Website:
        <a
          :href="itemData.Website"
          target="_blank"
        >
          {{ itemData.Website }}
        </a>
      </p>
    </div>
  </div>
</template>
<script>
export default {
  props: {
    itemData: {
      type: Object,
      default: () => {}
    }
  }
};
</script>
