// apps/demos/Demos/Scheduler/CurrentTimeIndicator/Vue/AppointmentTemplate.vue
<template>
  <div class="movie">
    <img
      :src="movieInfo.image"
      :alt="`${movieInfo.text} poster`"
    >
    <div class="movie-text">{{ movieInfo.text }}</div>
  </div>
</template>

<script setup lang="ts">
import { query as Query } from 'devextreme-vue/common/data';
import { type DxSchedulerTypes } from 'devextreme-vue/scheduler';
import { moviesData } from './data.ts';

const props = defineProps<{
  appointmentModel: DxSchedulerTypes.AppointmentTemplateData
}>();

const getMovieInfo = function (data: DxSchedulerTypes.Appointment) {
  return Query(moviesData)
    .filter(['id', data.movieId])
    .toArray()[0] || {};
};
const movieInfo = getMovieInfo(props.appointmentModel.appointmentData);

</script>

// apps/demos/Demos/Scheduler/CurrentTimeIndicator/React/AppointmentTemplate.tsx
import React from 'react';
import { query as Query } from 'devextreme-react/common/data';
import { type SchedulerTypes } from 'devextreme-react/scheduler';
import { moviesData } from './data.ts';

type AppointmentTemplateProps = {
  data: { appointmentData: SchedulerTypes.Appointment; };
};

const getMovieById = (id) => Query(moviesData).filter(['id', id]).toArray()[0];

const AppointmentTemplate = (props: AppointmentTemplateProps) => {
  const { appointmentData } = props.data;

  const movieInfo = getMovieById(appointmentData.movieId) || {};

  return (
    <div className="movie">
      <img src={movieInfo.image} alt={movieInfo.text + ' poster'} />
      <div className="movie-text">{movieInfo.text}</div>
    </div>
  );
};

export default AppointmentTemplate;
