// Demos/DataGrid/AdvancedMasterDetailView/React/AddressTab.js
import React from 'react';
import { Form, Item } from 'devextreme-react/form';

const items = ['Address', 'City', 'Region', 'PostalCode', 'Country', 'Phone'];

const renderFormItem = (item) => (
  <span>{item.editorOptions.value}</span>
);

const AddressTab = (props) => (
  <Form
    formData={props.data}
    colCount={2}
    className="address-form form-container"
  >
    {
      items.map((item, index) => <Item
        dataField={item}
        key={index}
        render={renderFormItem}
      />)
    }
  </Form>
);

export default AddressTab;

// Demos/DataGrid/AdvancedMasterDetailView/Vue/AddressTab.vue
<template>
  <DxForm
    :form-data="data"
    :items="items"
    :col-count="2"
    :customize-item="customizeItem"
    class="address-form form-container"
  >
    <template #form-item="{ data: item }">
      <span>
        {{ item.editorOptions.value }}
      </span>
    </template>
  </DxForm>
</template>

<script setup lang="ts">
import { DxForm } from 'devextreme-vue/form';

defineProps<{
  data: object
}>();

const items = ['Address', 'City', 'Region', 'PostalCode', 'Country', 'Phone'];

const customizeItem = (item) => {
  item.template = 'form-item';
};
</script>
