// Demos/DataGrid/AdvancedMasterDetailView/React/OrderHistory.js
import React from 'react';

import {
  Column, DataGrid, Paging, Summary, TotalItem, ValueFormat,
} from 'devextreme-react/data-grid';
import { createStore } from 'devextreme-aspnet-data-nojquery';

const url = 'https://js.devexpress.com/Demos/Mvc/api/DataGridAdvancedMasterDetailView';

const OrderHistory = ({ productId }) => {
  const [orderHistoryStore, setOrderHistoryStore] = React.useState(null);

  React.useEffect(() => {
    if (productId) {
      const newOrderHistoryStore = createStore({
        key: 'OrderID',
        loadParams: { ProductID: productId },
        loadUrl: `${url}/GetOrdersByProduct`,
      });
      setOrderHistoryStore(newOrderHistoryStore);
    }
  }, [productId]);

  return (
    <DataGrid
      dataSource={orderHistoryStore}
      showBorders={true}
    >
      <Paging defaultPageSize={5} />

      <Column dataField="OrderID" />
      <Column dataField="OrderDate" dataType="date" />
      <Column dataField="ShipCountry" />
      <Column dataField="ShipCity" />
      <Column dataField="UnitPrice" format="currency" />
      <Column dataField="Quantity" />
      <Column dataField="Discount" format="percent" />

      <Summary>
        <TotalItem column="UnitPrice" summaryType="sum">
          <ValueFormat format="currency" precision={2} />
        </TotalItem>
        <TotalItem column="Quantity" summaryType="count" />
      </Summary>

    </DataGrid>
  );
};

export default OrderHistory;

// Demos/DataGrid/AdvancedMasterDetailView/Vue/OrderHistory.vue
<template>
  <div>
    <DxDataGrid
      :data-source="orderHistoryStore"
      :show-borders="true"
    >
      <DxPaging :page-size="5"/>

      <DxColumn data-field="OrderID"/>
      <DxColumn
        data-field="OrderDate"
        data-type="date"
      />
      <DxColumn data-field="ShipCountry"/>
      <DxColumn data-field="ShipCity"/>
      <DxColumn
        data-field="UnitPrice"
        format="currency"
      />
      <DxColumn data-field="Quantity"/>
      <DxColumn
        data-field="Discount"
        format="percent"
      />

      <DxSummary>
        <DxTotalItem
          column="UnitPrice"
          summary-type="sum"
        >
          <DxValueFormat
            :precision="2"
            format="currency"
          />
        </DxTotalItem>
        <DxTotalItem
          column="Quantity"
          summary-type="count"
        />
      </DxSummary>
    </DxDataGrid>
  </div>
</template>

<script setup lang="ts">
import {
  DxDataGrid, DxColumn, DxPaging, DxSummary, DxTotalItem, DxValueFormat,
} from 'devextreme-vue/data-grid';
import { createStore } from 'devextreme-aspnet-data-nojquery';
import { computed } from 'vue';

const props = defineProps<{
  productId: number | null
}>();

const url = 'https://js.devexpress.com/Demos/Mvc/api/DataGridAdvancedMasterDetailView';

const orderHistoryStore = computed(() => (props.productId === null ? null : {
  store: createStore({
    key: 'OrderID',
    loadParams: { ProductID: props.productId },
    loadUrl: `${url}/GetOrdersByProduct`,
  }),
}));
</script>
