// Demos/DataGrid/AdvancedMasterDetailView/ReactJs/ProductSelectBox.js
import React from 'react';
import { SelectBox } from 'devextreme-react/select-box';
import { createStore } from 'devextreme-aspnet-data-nojquery';

const url = 'https://js.devexpress.com/Demos/Mvc/api/DataGridAdvancedMasterDetailView';
const productLabel = { 'aria-label': 'Product' };
const ProductSelectBox = (props) => {
  const [productsData, setProductsData] = React.useState(null);
  const valueChanged = React.useCallback(
    (e) => {
      props.onProductChanged(e.value);
    },
    [props],
  );
  React.useEffect(() => {
    const setDefaultValue = (items) => {
      const firstItem = items[0];
      if (firstItem && props.productId === null) {
        props.onProductChanged(firstItem.ProductID);
      }
    };
    const newProductsData = createStore({
      key: 'ProductID',
      loadParams: { SupplierID: props.supplierId },
      loadUrl: `${url}/GetProductsBySupplier`,
      onLoaded: setDefaultValue,
    });
    setProductsData(newProductsData);
  }, [props]);
  return (
    <SelectBox
      value={props.productId}
      deferRendering={false}
      inputAttr={productLabel}
      dataSource={productsData}
      valueExpr="ProductID"
      displayExpr="ProductName"
      onValueChanged={valueChanged}
    />
  );
};
export default ProductSelectBox;

// Demos/DataGrid/AdvancedMasterDetailView/Vue/ProductSelectBox.vue
<template>
  <DxSelectBox
    :defer-rendering="false"
    :data-source="dataSource"
    :input-attr="{ 'aria-label': 'Product' }"
    :value="productId"
    value-expr="ProductID"
    display-expr="ProductName"
    @valueChanged="$emit('product-changed', $event.value)"
  />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import DxSelectBox from 'devextreme-vue/select-box';
import { createStore } from 'devextreme-aspnet-data-nojquery';

defineEmits(['product-changed']);

const props = defineProps<{
  supplierId: number
}>();

const url = 'https://js.devexpress.com/Demos/Mvc/api/DataGridAdvancedMasterDetailView';

const dataSource = createStore({
  key: 'ProductID',
  loadParams: { SupplierID: props.supplierId },
  loadUrl: `${url}/GetProductsBySupplier`,
  onLoaded: setDefaultValue,
});

const productId = ref(null);

function setDefaultValue(items) {
  const firstItem = items[0];

  if (firstItem && productId.value === null) {
    productId.value = firstItem.ProductID;
  }
}
</script>
