// apps/demos/Demos/Form/ItemCustomization/React/LabelNotesTemplate.tsx
import React from 'react';
import { Tooltip } from 'devextreme-react/tooltip';

function LabelNotesTemplate(data) {
  return (
    <React.Fragment>
      <div id="template-content">
        <i id="helpedInfo" className="dx-icon dx-icon-info"></i>
        Additional
        <br />
        { data.text }
      </div>

      <Tooltip
        target="#helpedInfo"
        showEvent="mouseenter"
        hideEvent="mouseleave"
      >
        <div id="tooltip-content">This field must not exceed 200 characters</div>
      </Tooltip>
    </React.Fragment>
  );
}

export default LabelNotesTemplate;

// Demos/Form/CustomizeItem/Vue/LabelNotesTemplate.vue
<template>
  <span>
    <i class="dx-icon dx-icon-comment"/>Additional
    <br>
    <i
      id="helpedInfo"
      class="dx-icon dx-icon-info"
    />{{ data.text }}
    <DxTooltip
      target="#helpedInfo"
      show-event="mouseenter"
      hide-event="mouseleave"
    >
      <template #content>
        <b>This field must not exceed 200 characters</b>
      </template>
    </DxTooltip>
  </span>
</template>
<script>
import { DxTooltip } from 'devextreme-vue/tooltip';

export default {
  components: {
    DxTooltip,
  },
  props: {
    data: {
      type: Object,
      default: () => {},
    },
  },
};
</script>
<style scoped>
#helpedInfo {
  color: #42a5f5;
}
</style>
