// Demos/Popup/Overview/ReactJs/EmployeeItem.js
import React from 'react';
import { Button } from 'devextreme-react/button';

export function EmployeeItem(props) {
  const showInfo = React.useCallback(() => {
    props.showInfo(props.employee);
  }, [props]);
  return (
    <React.Fragment>
      <img
        alt={`${props.employee.FirstName} ${props.employee.LastName}`}
        src={props.employee.Picture}
        id={`image${props.employee.ID}`}
      />
      <br />
      <i>
        {props.employee.FirstName} {props.employee.LastName}
      </i>
      <br />
      <Button
        className="button-info"
        text="Details"
        onClick={showInfo}
      />
    </React.Fragment>
  );
}

// Demos/Popup/Overview/Vue/EmployeeItem.vue
<template>
  <li>
    <img
      :alt="employee.FirstName + ' ' + employee.LastName"
      :src="employee.Picture"
      :id="'image' + employee.ID"
    ><br>
    <i>{{ employee.FirstName }} {{ employee.LastName }}</i><br>
    <DxButton
      :on-click="showEmployeeInfo"
      class="button-info"
      text="Details"
    />
  </li>
</template>
<script>
import { DxButton } from 'devextreme-vue/button';

export default {
  components: {
    DxButton,
  },

  props: {
    employee: {
      type: Object,
      required: true,
      default: () => ({}),
    },
    showInfo: {
      type: Function,
      required: true,
      default: () => {},
    },
  },

  methods: {
    showEmployeeInfo() {
      this.showInfo(this.employee);
    },
  },
};
</script>
