// playgrounds/react/examples/text-box-example.tsx
/* eslint-disable react/no-unused-state */
import * as React from 'react';
import dxTextBox from 'devextreme/ui/text_box';
import { Button } from 'devextreme-react/button';
import { TextBox } from 'devextreme-react/text-box';
import { RequiredRule, Validator } from 'devextreme-react/validator';
import Example from './example-block';

export default class extends React.Component<any, { text: string; uncontrolledText: string; }> {
  private textBox: dxTextBox;

  constructor(props: unknown) {
    super(props);
    this.state = {
      text: 'text',
      uncontrolledText: 'initial text',
    };

    this.handleChange = this.handleChange.bind(this);
    this.updateUncontrolledValue = this.updateUncontrolledValue.bind(this);
    this.setFocusToTextBox = this.setFocusToTextBox.bind(this);
  }

  private handleChange(e: any) {
    this.setState({
      text: `#${(e.value as string).toUpperCase().replace('A', '_')}`,
    });
  }

  private setFocusToTextBox() {
    this.textBox.focus();
  }

  private updateUncontrolledValue() {
    this.setState({
      uncontrolledText: `#${this.textBox.option('value')}`,
    });
  }

  public render(): React.ReactNode {
    const { text } = this.state;
    return (
      <Example title="DxTextBox" state={this.state}>
        uncontrolled mode
        <TextBox
          defaultValue="initial text"
          ref={(ref) => {
            if (ref) {
              this.textBox = ref.instance;
            }
          }}
        />
        <br />
        <Button onClick={this.setFocusToTextBox} text="Set focus" />
        <Button onClick={this.updateUncontrolledValue} text="Update text" />
        <br />
        <br />
        controlled state value
        <TextBox value={text} valueChangeEvent="input" />
        <br />
        controlled state value with change handling
        <TextBox value={text} onValueChanged={this.handleChange} valueChangeEvent="input" />
        <br />
        validation (required)
        <TextBox valueChangeEvent="input" defaultValue="required text">
          <Validator>
            <RequiredRule message="this is required" />
          </Validator>
        </TextBox>
      </Example>
    );
  }
}

// components/text-box-example.vue
<template>
  <example-block title="dxTextBox" :state="$data">
    <h5 class="text-box-label">v-bind</h5>
    <dx-text-box
    :value="text"
    valueChangeEvent="input"
    />
    <h5 class="text-box-label">@update:value</h5>
    <dx-text-box
    @update:value="text = $event"
    valueChangeEvent="input"
    />
    <h5 class="text-box-label">@valueChanged</h5>
    <dx-text-box
    @valueChanged="text = $event.value"
    valueChangeEvent="input"
    />
    <h5 class="text-box-label">@value-changed</h5>
    <dx-text-box
      @value-changed="text = $event.value"
      valueChangeEvent="input"
    />
    <h5 class="text-box-label">v-model</h5>
    <dx-text-box
    v-model:value="text"
    valueChangeEvent="input"
    />
    <h5 class="text-box-label">@focusIn (clears text)</h5>
    <dx-text-box
    v-model:value="text"
    @focusIn="text = ''"
    valueChangeEvent="input" />
    <h5 class="text-box-label">Validation (Required)</h5>
    <dx-text-box value="Required text">
      <dx-validator :validationRules="rules" />
    </dx-text-box>
  </example-block>
</template>

<script>
import ExampleBlock from "./example-block";

import { DxTextBox, DxValidator } from "devextreme-vue";

export default {
  components: {
    ExampleBlock,
    DxTextBox,
    DxValidator
  },
  data: function () {
    return {
      text: "text",
      rules: [
        {
          type: "required",
          message: "this is required"
        }
      ]
    };
  }
};
</script>

<style scoped>
.text-box-label {
  font-weight: 900;
  margin-top: 20px;
}
</style>
