// apps/demos/Demos/Charts/AreaSparklines/ReactJs/RowTemplate.js
import React from 'react';
import Sparkline, { Tooltip } from 'devextreme-react/sparkline';
import { copperCosts, nickelCosts, palladiumCosts } from './data.js';

export default function RowTemplate(props) {
  return (
    <tr>
      <th>{props.year}</th>
      <td>
        <Sparkline
          dataSource={copperCosts}
          showMinMax={true}
          className="sparkline"
          argumentField="month"
          valueField={props.year}
          type="area"
        >
          <Tooltip format={{ type: 'currency', precision: 2 }} />
        </Sparkline>
      </td>
      <td>
        <Sparkline
          dataSource={nickelCosts}
          pointSize={6}
          showMinMax={true}
          showFirstLast={false}
          className="sparkline"
          argumentField="month"
          valueField={props.year}
          type="splinearea"
          lineColor="#8076bb"
          minColor="#6babac"
          maxColor="#8076bb"
        >
          <Tooltip format={{ type: 'currency', precision: 2 }} />
        </Sparkline>
      </td>
      <td>
        <Sparkline
          dataSource={palladiumCosts}
          lineWidth={3}
          className="sparkline"
          argumentField="month"
          valueField={props.year}
          type="steparea"
          lineColor="#7e4452"
          firstLastColor="#e55253"
          pointColor="#e8c267"
          pointSymbol="polygon"
        >
          <Tooltip format={{ type: 'currency', precision: 2 }} />
        </Sparkline>
      </td>
    </tr>
  );
}

// apps/demos/Demos/Charts/AreaSparklines/Vue/RowTemplate.vue
<template>
  <tr class="rows-content">
    <th>{{ year }}</th>
    <td>
      <DxSparkline
        :data-source="copperCosts"
        :show-min-max="true"
        :value-field="year"
        class="sparkline"
        argument-field="month"
        type="area"
      >
        <DxTooltip :format="{ type: 'currency', precision: 2 }"/>
      </DxSparkline>
    </td>
    <td>
      <DxSparkline
        :data-source="nickelCosts"
        :point-size="6"
        :show-min-max="true"
        :show-first-last="false"
        :value-field="year"
        class="sparkline"
        argument-field="month"
        type="splinearea"
        line-color="#8076bb"
        min-color="#6babac"
        max-color="#8076bb"
      >
        <DxTooltip :format="{ type: 'currency', precision: 2 }"/>
      </DxSparkline>
    </td>
    <td>
      <DxSparkline
        :data-source="palladiumCosts"
        :line-width="3"
        :value-field="year"
        class="sparkline"
        argument-field="month"
        type="steparea"
        line-color="#7e4452"
        first-last-color="#e55253"
        point-color="#e8c267"
        point-symbol="polygon"
      >
        <DxTooltip :format="{ type: 'currency', precision: 2 }"/>
      </DxSparkline>
    </td>
  </tr>
</template>

<script setup lang="ts">
import DxSparkline, {
  DxTooltip,
} from 'devextreme-vue/sparkline';
import {
  copperCosts,
  nickelCosts,
  palladiumCosts,
} from './data.ts';

withDefaults(defineProps<{
  year?: string
}>(), {
  year: '',
});
</script>

<style>
.rows-content td {
  font-weight: 400;
  width: 200px;
  padding: 25px 10px 5px;
  border: 1px solid #c2c2c2;
}

.rows-content tr:nth-child(2) td {
  border-top: 1px solid #c2c2c2;
}

.rows-content td:first-of-type {
  border-left: 1px solid #c2c2c2;
}

.rows-content .sparkline {
  width: 200px;
  height: 30px;
}
</style>
