// apps/demos/Demos/Accordion/Overview/Vue/CustomItem.vue
<template>
  <div>
    <div>
      <p>
        <b>{{ itemData.City }}</b>
        (<span>{{ itemData.State }}</span>)
      </p>
      <p>
        <span>{{ itemData.Zipcode }}&nbsp;</span>
        <span>{{ itemData.Address }}</span>
      </p>
    </div>
    <div>
      <p>
        Phone: <b>{{ itemData.Phone }}</b>
      </p>
      <p>
        Fax: <b>{{ itemData.Fax }}</b>
      </p>
      <p>
        Website:
        <a
          :href="itemData.Website"
          target="_blank"
        >
          {{ itemData.Website }}
        </a>
      </p>
    </div>
  </div>
</template>
<script setup lang="ts">
import { type CompanyData } from './data.ts';

defineProps<{
  itemData: CompanyData
}>();
</script>

// apps/demos/Demos/Accordion/Overview/ReactJs/CustomItem.js
import React from 'react';

export default function CustomItem(data) {
  return (
    <div>
      <div>
        <p>
          <b>{data.City} </b>(<span>{data.State}</span>)
        </p>
        <p>
          <span>{data.Zipcode} </span>
          <span>{data.Address}</span>
        </p>
      </div>
      <div>
        <p>
          Phone: <b>{data.Phone}</b>
        </p>
        <p>
          Fax: <b>{data.Fax}</b>
        </p>
        <p>
          Website:{' '}
          <a
            href={data.Website}
            target="_blank"
          >
            {data.Website}
          </a>
        </p>
      </div>
    </div>
  );
}
