// packages/devextreme/js/__internal/core/r1/runtime/react/template.tsx
import ReactDOM from 'react-dom';
import * as React from 'react';

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const renderTemplate = (template: any, model: any, _component?: any): void => {
  const TemplateProp = template;
  const container = model.container ? model.container : model.item;

  if (typeof TemplateProp !== 'string' || !(template instanceof Element)) {
    ReactDOM.render(
      /* eslint-disable react/jsx-props-no-spreading */
      <TemplateProp {...model} /> as React.ReactElement,
      container ? model.container : model.item,
    );
  }
};

export const hasTemplate = (
  name: string,
  props: Record<string, unknown>,
  _component?: any,
): boolean => {
  const value = props[name];
  return !!value && typeof value !== 'string';
};

export const getTemplate = (TemplateProp: any, RenderProp: any, ComponentProp: any): any => {
  if (TemplateProp) {
    return TemplateProp.defaultProps ? (props: any) => <TemplateProp {...props} /> : TemplateProp;
  } if (RenderProp) {
    return (props: any) => RenderProp(
      ...('data' in props ? [props.data, props.index] : [props]),
    );
  } if (ComponentProp) {
    return (props: any) => <ComponentProp {...props} />;
  }
  return '';
};

// packages/devextreme/runtime/angular/template.ts
import { ViewContainerRef } from '@angular/core';

interface IModel {
  item: HTMLElement & { get: (index: number) => HTMLElement } | any,
  index: number,
  container: HTMLElement & { get?: (index: number) => HTMLElement }
}

const getContainer = (props: IModel): HTMLElement => {
  const container = props.container || props.item;
  return container?.get ? container?.get(0) : container;
};

export const renderTemplate = (
  template: any,
  model: IModel,
  component?: any,
): void => {
  const childView = (component.viewContainerRef as ViewContainerRef).createEmbeddedView(template, {
    $implicit: model.item,
    index: model.index,
  });
  const container = getContainer(model);
  if (container) {
    childView.rootNodes.forEach((element) => {
      component.renderer.appendChild(container, element);
    });
  }
};
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const hasTemplate = (
  name: string,
  props: Record<string, unknown>,
  _component?: any,
): boolean => {
  const value = props[name];
  return !!value && typeof value !== 'string';
};
