// apps/demos/Demos/TabPanel/Overview/ReactJs/TabPanelItem.js
import React from 'react';
import TaskItem from './TaskItem.js';

function TabPanelItem({ data }) {
  const taskItems = data.tasks.map((task, index) => (
    <TaskItem
      key={index}
      task={task}
    />
  ));
  return <div className="tabpanel-item">{taskItems}</div>;
}
export default TabPanelItem;

// apps/demos/Demos/TabPanel/Overview/Vue/TabPanelItem.vue
<template>
  <div>
    <div class="tabpanel-item">
      <TaskItem
        v-for="(task, index) in tasks"
        :key="index"
        :task="task"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import TaskItem from './TaskItem.vue';

withDefaults(defineProps<{
  tasks?: Record<string, any>[]
}>(), {
  tasks: () => [],
});
</script>

<style>
.tabpanel-item {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 24px;
}
</style>
