// apps/demos/Demos/FilterBuilder/Customization/Vue/EditorComponent.vue
<template>
  <DxTagBox
    :value="conditionInfo.value"
    :items="categories"
    :input-attr="{ 'aria-label': 'Category' }"
    width="auto"
    @value-changed="onValueChanged"
  />
</template>

<script setup lang="ts">
import DxTagBox from 'devextreme-vue/tag-box';
import { categories } from './data.ts';

const props = withDefaults(defineProps<{
  conditionInfo?: Record<string, any>
}>(), {
  conditionInfo: () => ({} as Record<string, any>),
});

function onValueChanged(e) {
  props.conditionInfo.setValue(e.value && e.value.length ? e.value : null);
}
</script>

// apps/demos/Demos/FilterBuilder/Customization/ReactJs/EditorComponent.js
import React, { useCallback } from 'react';
import TagBox from 'devextreme-react/tag-box';
import { categories, categoryLabel } from './data.js';

export const EditorComponent = (props) => {
  const onValueChanged = useCallback(
    (e) => {
      props.data.setValue(e.value && e.value.length ? e.value : null);
    },
    [props.data],
  );
  return (
    <TagBox
      inputAttr={categoryLabel}
      defaultValue={props.data.value}
      items={categories}
      onValueChanged={onValueChanged}
      width="auto"
    />
  );
};
