// Demos/FilterBuilder/Customization/Vue/EditorComponent.vue
<template>
  <DxTagBox
    :value="conditionInfo.value"
    :items="categories"
    width="auto"
    @value-changed="onValueChanged"
  />
</template>

<script>
import DxTagBox from 'devextreme-vue/tag-box';
import { categories } from './data.js';

export default {
  components: {
    DxTagBox,
  },
  props: {
    conditionInfo: {
      type: Object,
      default: () => {},
    },
  },
  data() {
    return {
      categories,
    };
  },
  methods: {
    onValueChanged(e) {
      this.conditionInfo.setValue(e.value && e.value.length ? e.value : null);
    },
  },
};
</script>

// apps/demos/Demos/FilterBuilder/Customization/React/EditorComponent.tsx
import React, { useCallback } from 'react';
import TagBox, { type TagBoxTypes } from 'devextreme-react/tag-box';
import { categories, categoryLabel } from './data.ts';

export const EditorComponent = (props: { data: { value: any, setValue: (value: any) => void } }) => {
  const onValueChanged = useCallback((e: TagBoxTypes.ValueChangedEvent) => {
    props.data.setValue(e.value?.length ? e.value : null);
  }, [props.data]);

  return (
    <TagBox
      inputAttr={categoryLabel}
      defaultValue={props.data.value}
      items={categories}
      onValueChanged={onValueChanged}
      width="auto"
    />
  );
};
