// Demos/FilterBuilder/Customization/Vue/EditorComponent.vue
<template>
  <DxTagBox
    :value="conditionInfo.value"
    :items="categories"
    width="auto"
    @value-changed="onValueChanged"
  />
</template>

<script>
import DxTagBox from 'devextreme-vue/tag-box';
import { categories } from './data.js';

export default {
  components: {
    DxTagBox,
  },
  props: {
    conditionInfo: {
      type: Object,
      default: () => {},
    },
  },
  data() {
    return {
      categories,
    };
  },
  methods: {
    onValueChanged(e) {
      this.conditionInfo.setValue(e.value && e.value.length ? e.value : null);
    },
  },
};
</script>

// Demos/FilterBuilder/Customization/React/EditorComponent.js
import React from 'react';
import TagBox from 'devextreme-react/tag-box';
import { categories } from './data.js';

export class EditorComponent extends React.Component {
  constructor(props) {
    super(props);
    this.onValueChanged = this.onValueChanged.bind(this);
  }
  render() {
    return (
      <TagBox
        defaultValue={this.props.data.value}
        items={categories}
        onValueChanged={this.onValueChanged}
        width="auto"
      />
    );
  }
  onValueChanged(e) {
    this.props.data.setValue(e.value && e.value.length ? e.value : null);
  }
}
