// apps/demos/Demos/Chat/PageLevelAIAssistant/ReactJs/TaskGrid.js
import React from 'react';
import DataGrid, { Column, FilterRow, HeaderFilter, LoadPanel, } from 'devextreme-react/data-grid';
import { tasks } from './data.js';
const completionEditorOptions = {
    elementAttr: { 'aria-label': 'Completed' },
};
function renderPriorityCell({ value }) {
    return <div className={`priority-badge priority-badge--${value.toLowerCase()}`}>{value}</div>;
}
const calculateCompletion = (row) => row.Completion === 100;
const calculateFilterExpression = (filterValue, operation) => {
    const wantsCompleted = operation === '<>' ? !filterValue : !!filterValue;
    const rawCompletion = (rowData) => rowData.Completion;
    return [rawCompletion, wantsCompleted ? '=' : '<', 100];
};
export default function TaskGrid({ gridRef }) {
    return (<div id="grid-container">
      <DataGrid ref={gridRef} dataSource={tasks} keyExpr="ID" height={360} showBorders={true} filterSyncEnabled={true}>
        <FilterRow visible={true}/>
        <HeaderFilter visible={true}/>
        <LoadPanel enabled={true}/>
        <Column dataField="Subject" width={250}/>
        <Column dataField="StartDate" dataType="date"/>
        <Column dataField="DueDate" dataType="date"/>
        <Column dataField="Priority" caption="Priority" cellRender={renderPriorityCell}/>
        <Column dataField="Completion" caption="Completed" alignment="center" dataType="boolean" editorOptions={completionEditorOptions} calculateCellValue={calculateCompletion} calculateFilterExpression={calculateFilterExpression}/>
      </DataGrid>
    </div>);
}

// apps/demos/Demos/Chat/CustomAIAssistant/Vue/TaskGrid.vue
<template>
  <DxDataGrid
    ref="dataGridRef"
    id="grid-container"
    :dataSource="tasks"
    keyExpr="ID"
    :showBorders="true"
    :filterSyncEnabled="true"
  >
    <DxFilterRow :visible="true"/>
    <DxHeaderFilter :visible="true"/>

    <DxColumn
      dataField="Subject"
      :width="250"
    />
    <DxColumn
      dataField="StartDate"
      dataType="date"
    />
    <DxColumn
      dataField="DueDate"
      dataType="date"
    />
    <DxColumn
      dataField="Priority"
      caption="Priority"
      cellTemplate="priority-cell"
    />
    <template #priority-cell="{ data }">
      <div
        class="priority-badge"
        :style="{ background: priorityColor(data.value) }"
      >{{ data.value }}</div>
    </template>
    <DxColumn
      dataField="Completion"
      caption="Completed"
      alignment="center"
      dataType="boolean"
      :editorOptions="completionEditorOptions"
      :calculateCellValue="calculateCompletionCellValue"
      :calculateFilterExpression="calculateCompletionFilterExpression"
    />
  </DxDataGrid>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { DxDataGrid, DxColumn, DxFilterRow, DxHeaderFilter } from 'devextreme-vue/data-grid';
import { colors, tasks } from './data.ts';
import type { ColumnFilterExpression, Task, TaskPriority } from './types';

const dataGridRef = ref<InstanceType<typeof DxDataGrid>>();

const completionEditorOptions = {
  elementAttr: { 'aria-label': 'Completed' },
};

function priorityColor(value: TaskPriority): string {
  return colors[value];
}

function calculateCompletionCellValue(rowData: Task): boolean {
  return rowData.Completion === 100;
}

function calculateCompletionFilterExpression(
  filterValue: unknown,
  selectedFilterOperation: string | null,
): ColumnFilterExpression {
  const wantsCompleted = selectedFilterOperation === '<>' ? !filterValue : !!filterValue;
  const rawCompletion = (rowData: Task): number => rowData.Completion;

  return wantsCompleted ? [rawCompletion, '=', 100] : [rawCompletion, '<', 100];
}

defineExpose({
  get instance() {
    return dataGridRef.value!.instance;
  },
});
</script>

<style scoped>
#grid-container {
  margin-top: 20px;
  min-height: 360px;
}

.priority-badge {
  border-radius: 24px;
  padding: 2px 8px;
  display: inline-block;
  text-align: center;
}
</style>
