// Demos/Scheduler/CellTemplates/Vue/DataCell.vue
<template>
  <div :class="markDataCell(cellData)"/>
</template>
<script>
import Utils from './utils.js';

export default {
  props: {
    cellData: {
      type: Object,
      default: () => {},
    },
  },
  methods: {
    markDataCell(cellData) {
      const date = cellData.startDate;
      const isDisableDate = Utils.isHoliday(date) || Utils.isWeekend(date);
      const isDinner = !isDisableDate && Utils.isDinner(date);

      return {
        'disable-date': isDisableDate,
        dinner: isDinner,
      };
    },
  },
};
</script>

// apps/demos/Demos/Scheduler/CellTemplates/React/DataCell.tsx
import React from 'react';
import Utils from './utils.ts';

type DataCellProps = {
  className: string
  data: {
    startDate: Date;
  }
};

const DataCell = (props: React.PropsWithChildren<DataCellProps>) => {
  const { startDate } = props.data;
  const isDinner = Utils.isDinner(startDate);
  let cssClasses = props.className || '';

  if (Utils.isDisableDate(startDate)) {
    cssClasses += ' disable-date';
  } else if (isDinner) {
    cssClasses += ' dinner';
  }

  return (
    <div className={cssClasses}>
      {props.children}
    </div>
  );
};

export default DataCell;
