// apps/demos/Demos/Stepper/FormIntegration/Angular/app/confirmation/confirmation.component.ts
import { Component, Input } from '@angular/core';
import type { BookingFormData } from '../app.types';

@Component({
  selector: 'confirmation',
  templateUrl: './confirmation.component.html',
  styleUrls: ['./confirmation.component.css'],
})
export class ConfirmationComponent {
  @Input() formData: BookingFormData;

  @Input() isConfirmed: boolean;

  getCheckInDate() {
    return new Date(this.formData.dates[0]).toLocaleDateString();
  }

  getCheckOutDate() {
    return new Date(this.formData.dates[1]).toLocaleDateString();
  }
}

<div class="summary-item-header center" *ngIf="isConfirmed">
  Your booking request was submitted.
</div>
<div class="summary-container" *ngIf="!isConfirmed">
  <div class="summary-item">
    <div class="summary-item-header">Dates</div>
    <div class="separator"></div>
    <div>
      <span class="summary-item-label">Check-in Date: </span
      >{{ getCheckInDate() }}
    </div>
    <div>
      <span class="summary-item-label">Check-out Date: </span
      >{{ getCheckOutDate() }}
    </div>
  </div>

  <div class="summary-item">
    <div class="summary-item-header">Guests</div>
    <div class="separator"></div>
    <div
      ><span class="summary-item-label">Adults: </span
      >{{ formData.adultsCount }}</div
    >
    <div
      ><span class="summary-item-label">Children: </span
      >{{ formData.childrenCount }}</div
    >
    <div
      ><span class="summary-item-label">Pets: </span
      >{{ formData.petsCount }}</div
    >
  </div>

  <div class="summary-item">
    <div class="summary-item-header">Room and Meals</div>
    <div class="separator"></div>
    <div
      ><span class="summary-item-label">Room Type: </span
      >{{ formData.roomType }}</div
    >
    <div
      ><span class="summary-item-label">Check-out Date: </span
      >{{ formData.mealPlan }}</div
    >
  </div>

  <div class="summary-item" *ngIf="!!formData.additionalRequest">
    <div class="summary-item-header">Additional Requests</div>
    <div class="separator"></div>
    <div>{{ formData.additionalRequest }}</div>
  </div>
</div>

// apps/demos/Demos/Stepper/FormIntegration/React/Confirmation.tsx
import React from 'react';
import type { FC } from 'react';

import type { BookingFormData } from './types.ts';

interface ConfirmationProps {
  formData: BookingFormData;
  isConfirmed: boolean;
}

const Confirmation: FC<ConfirmationProps> = ({ formData, isConfirmed }: ConfirmationProps) => {
  if (isConfirmed) {
    return (
      <div className="summary-item-header center">
        Your booking request was submitted.
      </div>
    );
  }

  return (
    <div className="summary-container">
      <div className="summary-item">
        <div className="summary-item-header">Dates</div>
        <div className="separator"></div>
        <div>
          <span className="summary-item-label">Check-in Date: </span>{new Date(formData.dates[0] ?? '').toLocaleDateString()}
        </div>
        <div>
          <span className="summary-item-label">Check-out Date: </span>{new Date(formData.dates[1] ?? '').toLocaleDateString()}
        </div>
      </div>

      <div className="summary-item">
        <div className="summary-item-header">Guests</div>
        <div className="separator"></div>
        <div><span className="summary-item-label">Adults: </span>{formData.adultsCount}</div>
        <div><span className="summary-item-label">Children: </span>{formData.childrenCount}</div>
        <div><span className="summary-item-label">Pets: </span>{formData.petsCount}</div>
      </div>

      <div className="summary-item">
        <div className="summary-item-header">Room and Meals</div>
        <div className="separator"></div>
        <div><span className="summary-item-label">Room Type: </span>{formData.roomType}</div>
        <div><span className="summary-item-label">Check-out Date: </span>{formData.mealPlan}</div>
      </div>

      {!!formData.additionalRequest && (
        <div className="summary-item">
          <div className="summary-item-header">Additional Requests</div>
          <div className="separator"></div>
          <div>{formData.additionalRequest}</div>
        </div>
      )}
    </div>
  );
};

Confirmation.displayName = 'Confirmation';

export default Confirmation;
