// apps/demos/Demos/Stepper/FormIntegration/Angular/app/dates-form/dates-form.component.ts
import { Component, Input } from '@angular/core';
import { DxFormTypes } from 'devextreme-angular/ui/form';
import { DxDateRangeBoxTypes } from 'devextreme-angular/ui/date-range-box';
import type { BookingFormData } from '../app.types';

let modulePrefix = '';
// @ts-ignore
if (window && window.config?.packageConfigPaths) {
  modulePrefix = '/app';
}

@Component({
  selector: 'dates-form',
  templateUrl: `.${modulePrefix}/dates-form/dates-form.component.html`,
})
export class DatesFormComponent {
  @Input() formData: BookingFormData;

  @Input() validationGroup: string;

  dateRangeBoxOptions: DxDateRangeBoxTypes.Properties = {
    startDatePlaceholder: 'Check-in',
    endDatePlaceholder: 'Check-out',
    elementAttr: { id: 'datesPicker' },
  }

  labelOptions: DxFormTypes.SimpleItem["label"] = {
    visible: false,
  };
}

<p>
  Select your check-in and check-out dates. If your dates are flexible, include
  that information in Additional Requests. We will do our best to suggest best
  pricing options, depending on room availability.
</p>
<dx-form [(formData)]="formData" [validationGroup]="validationGroup">
  <dxi-item
    [isRequired]="true"
    dataField="dates"
    editorType="dxDateRangeBox"
    [editorOptions]="dateRangeBoxOptions"
    [label]="labelOptions"
  >
    <dxi-validation-rule type="required"></dxi-validation-rule>
  </dxi-item>
</dx-form>

// apps/demos/Demos/Stepper/FormIntegration/React/DatesForm.tsx
import React, { memo } from 'react';
import type { FC } from 'react';
import 'devextreme-react/date-range-box';
import { Form, SimpleItem } from 'devextreme-react/form';

import type { FormProps } from './types.ts';

const DatesForm: FC<FormProps> = memo(({ formData, validationGroup }: FormProps) => (
  <>
    <p>
      Select your check-in and check-out dates. If your dates are flexible, include that information in Additional Requests. We will do our best to suggest best pricing options, depending on room availability.
    </p>
    <Form formData={formData} validationGroup={validationGroup}>
      <SimpleItem
        isRequired
        dataField='dates'
        editorType='dxDateRangeBox'
        editorOptions={{
          startDatePlaceholder: 'Check-in',
          endDatePlaceholder: 'Check-out',
          elementAttr: { id: 'datesPicker' },
        }}
        label={{ visible: false }}
      />
    </Form>
  </>
));

DatesForm.displayName = 'DatesForm';

export default DatesForm;
