// apps/demos/Demos/Stepper/FormIntegration/Angular/app/guests-form/guests-form.component.ts
import { Component, Input } from '@angular/core';
import { DxFormTypes } from 'devextreme-angular/ui/form';
import { DxNumberBoxTypes } from 'devextreme-angular/ui/number-box';
import type { BookingFormData } from '../app.types';

let modulePrefix = '';
// @ts-ignore
if (window && window.config?.packageConfigPaths) {
  modulePrefix = '/app';
}

@Component({
  selector: 'guests-form',
  templateUrl: `.${modulePrefix}/guests-form/guests-form.component.html`,
})
export class GuestsFormComponent {
  @Input() formData: BookingFormData;

  @Input() validationGroup: string;

  adultsLabelOptions: DxFormTypes.SimpleItem["label"] = {
    text: 'Adults',
    location: 'top',
  };

  childrenLabelOptions: DxFormTypes.SimpleItem["label"] = {
    text: 'Children',
    location: 'top',
  };

  petsLabelOptions: DxFormTypes.SimpleItem["label"] = {
    text: 'Pets',
    location: 'top',
  };

  numberBoxOptions: DxNumberBoxTypes.Properties = {
    min: 0,
    max: 5,
    showSpinButtons: true,
    elementAttr: { id: 'adultsCount' }
  };
}

<p>
  Enter the number of adults, children, and pets staying in the room. This
  information help us suggest suitable room types, number of beds, and included
  amenities.
</p>
<dx-form
  #formComponent
  [(formData)]="formData"
  [validationGroup]="validationGroup"
  [colCount]="3"
>
  <dxi-form-item
    [isRequired]="true"
    dataField="adultsCount"
    editorType="dxNumberBox"
    [editorOptions]="numberBoxOptions"
    [label]="adultsLabelOptions"
  >
    <dxi-form-validation-rule type="range" [min]="1"></dxi-form-validation-rule>
  </dxi-form-item>

  <dxi-form-item
    dataField="childrenCount"
    editorType="dxNumberBox"
    [editorOptions]="numberBoxOptions"
    [label]="childrenLabelOptions"
  >
  </dxi-form-item>

  <dxi-form-item
    dataField="petsCount"
    editorType="dxNumberBox"
    [editorOptions]="numberBoxOptions"
    [label]="petsLabelOptions"
  >
  </dxi-form-item>
</dx-form>

// apps/demos/Demos/Stepper/FormIntegration/React/GuestsForm.tsx
import React, { FC, memo } from 'react';
import { Form, RangeRule, SimpleItem } from 'devextreme-react/form';
import 'devextreme-react/number-box';

import { FormProps } from './types.ts';

const GuestsForm: FC<FormProps> = memo(({ formData, validationGroup }) => (
  <>
    <p>
      Enter the number of adults, children, and pets staying in the room. This information help us suggest suitable room types, number of beds, and included amenities.
    </p>

    <Form formData={formData} validationGroup={validationGroup} colCount={3}>
      <SimpleItem
        isRequired
        dataField='adultsCount'
        editorType='dxNumberBox'
        editorOptions={{
          elementAttr: { id: 'adultsCount' },
          showSpinButtons: true,
          min: 0,
          max: 5
        }}
        label={{ text: 'Adults', location: 'top' }}
      >
        <RangeRule min={1} />
      </SimpleItem>
      <SimpleItem
        dataField='childrenCount'
        editorType='dxNumberBox'
        editorOptions={{ showSpinButtons: true, min: 0, max: 5 }}
        label={{ text: 'Children', location: 'top' }}
      />
      <SimpleItem
        dataField='petsCount'
        editorType='dxNumberBox'
        editorOptions={{ showSpinButtons: true, min: 0, max: 5 }}
        label={{ text: 'Pets', location: 'top' }}
      />
    </Form>
  </>
));

GuestsForm.displayName = 'GuestsForm';

export default GuestsForm;
