// apps/demos/Demos/DataGrid/AIColumns/Angular/app/license-info/license-info.component.ts
import { Component, Input } from '@angular/core';
import { Vehicle } from '../app.service';

@Component({
  selector: 'license-info',
  templateUrl: './license-info.component.html',
})
export class LicenseInfo {
  vehicleLink = '';

  @Input() vehicle!: Vehicle;

  ngOnChanges(): void {
    this.vehicleLink = `https://${this.vehicle.Source}`;
  }
}

<p>
  <b>Image licensed under: </b>
  <span>{{ vehicle.LicenseName }}</span>
</p>
<p>
  <b>Author: </b>
  <span>{{ vehicle.Author }}</span>
</p>
<p>
  <b>Source link: </b>
  <a [href]="vehicleLink" target="_blank">{{ vehicleLink }}</a>
</p>
<p>
  <b>Edits: </b>
  <span>{{ vehicle.Edits }}</span>
</p>

// apps/demos/Demos/CardView/CardTemplate/ReactJs/LicenseInfo.js
import React from 'react';

const LicenseInfo = ({
  vehicle: {
    LicenseName, Author, Source, Edits,
  },
}) => {
  const vehicleLink = `https://${Source}`;
  return (
    <div>
      <p>
        <b>Image licensed under: </b> <span>{LicenseName}</span>
      </p>
      <p>
        <b>Author: </b> <span>{Author}</span>
      </p>
      <p>
        <b>Source link: </b>
        <a
          href={vehicleLink}
          target="_blank"
        >
          {vehicleLink}
        </a>
      </p>
      <p>
        <b>Edits: </b> <span>{Edits}</span>
      </p>
    </div>
  );
};
export default LicenseInfo;
