// apps/demos/Demos/CardView/CardTemplate/Vue/VehicleCard.vue
<template>
  <div class="vehicle__card">
    <div class="vehicle__img-wrapper">
      <img class="vehicle__img"
        :src="`../../../../images/vehicles/image_${vehicle.ID}.png`"
        :alt="`${vehicle.TrademarkName} ${vehicle.Name}`"
      >
    </div>
    <div class="vehicle__info">
      <div class="vehicle__name" :title="`${vehicle.TrademarkName} ${vehicle.Name}`">
        {{ vehicle.TrademarkName }} {{ vehicle.Name }}
      </div>
      <div class="vehicle__price">
        ${{ vehicle.Price }}
      </div>
      <div class="vehicle__type-container">
        <div class="vehicle__type">
          {{ vehicle.CategoryName }}
        </div>
      </div>
      <div class="vehicle__spec-container">
        <div class="vehicle__modification">
          {{ vehicle.Modification }}
        </div>
        <div class="vehicle__modification">
          {{ vehicle.BodyStyleName }} {{ vehicle.Horsepower }} h.p.
        </div>
      </div>
      <div class="vehicle__footer-container">
        <DxButton
          text="Image Info"
          type="default"
          width="100%"
          @click="$emit('show-info', vehicle)"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { DxButton } from 'devextreme-vue/button';

defineProps<{
  vehicle: any
}>();

defineEmits(['show-info']);
</script>

// apps/demos/Demos/CardView/CardTemplate/ReactJs/VehicleCard.js
import React from 'react';
import Button from 'devextreme-react/button';

const VehicleCard = ({
  vehicle: {
    ID,
    TrademarkName,
    Name,
    Price,
    CategoryName,
    Modification,
    BodyStyleName,
    Horsepower,
  },
  vehicle,
  onShowInfo,
}) => (
  <div className="vehicle__card">
    <div className="vehicle__img-wrapper">
      <img
        className="vehicle__img"
        src={`../../../../images/vehicles/image_${ID}.png`}
        alt={`${TrademarkName} ${Name}`}
      />
    </div>
    <div className="vehicle__info">
      <div
        className="vehicle__name"
        title={`${TrademarkName} ${Name}`}
      >
        {TrademarkName} {Name}
      </div>
      <div className="vehicle__price">${Price}</div>
      <div className="vehicle__type-container">
        <div className="vehicle__type">{CategoryName}</div>
      </div>
      <div className="vehicle__spec-container">
        <div className="vehicle__modification">{Modification}</div>
        <div className="vehicle__modification">{BodyStyleName}</div>
        <div className="vehicle__modification">{Horsepower} h.p.</div>
      </div>
      <div className="vehicle__footer-container">
        <Button
          text="Image Info"
          type="default"
          width="100%"
          onClick={() => onShowInfo(vehicle)}
        ></Button>
      </div>
    </div>
  </div>
);
export default VehicleCard;
