// apps/demos/Demos/TreeList/AIColumns/ReactJs/Employee.js
import React from 'react';

export default function Employee(props) {
  const { First_Name, Last_Name } = props.data;
  return (
    <div className="name__wrapper">
      <div className="name__img-wrapper">
        <img
          src={`../../../../images/employees/new/${First_Name} ${Last_Name}.jpg`}
          alt={`${First_Name} ${Last_Name}`}
        />
      </div>
      <div className="name__text-wrapper">
        <div className="name__text">{First_Name}</div>
        <div className="name__text">{Last_Name}</div>
      </div>
    </div>
  );
}

// apps/demos/Demos/TreeList/AIColumns/Angular/app/employee/employee.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'employee',
  templateUrl: './employee.component.html',
  styleUrls: ['./employee.component.css'],
})
export class Employee {
  @Input() firstName!: string;

  @Input() lastName!: string;
}

<div class="employee__wrapper">
  <div class="employee__img-wrapper">
    <img
      src="../../../../images/employees/new/{{ firstName }} {{ lastName }}.jpg"
      alt="{{ firstName }} {{ lastName }}"
    />
  </div>
  <div class="employee__text-wrapper">
    <div class="employee__text">{{ firstName }}</div>
    <div class="employee__text">{{ lastName }}</div>
  </div>
</div>
