// Demos/SelectBox/Overview/React/Field.js
import React from 'react';
import TextBox from 'devextreme-react/text-box';

export default function Field(data) {
  return (
    <div className="custom-item">
      <img src={data && data.ImageSrc} />
      <TextBox className="product-name"
        defaultValue={data && data.Name}
        readOnly={true} />
    </div>
  );
}

// Demos/SelectBox/Overview/Vue/Field.vue
<template>
  <div class="custom-item">
    <img
      v-if="fieldData"
      :src="fieldData.ImageSrc"
    >
    <DxTextBox
      :value="fieldData && fieldData.Name"
      :read-only="true"
      class="product-name"
    />
  </div>
</template>
<script>
import DxTextBox from 'devextreme-vue/text-box';

export default {
  components: {
    DxTextBox
  },
  props: {
    fieldData: {
      type: Object,
      default: () => {}
    }
  }
};
</script>
