// apps/demos/Demos/SelectBox/Overview/ReactJs/Field.js
import React from 'react';
import TextBox from 'devextreme-react/text-box';

const nameLabel = { 'aria-label': 'Name' };
export default function Field(data) {
  return (
    <div className="custom-item">
      <img
        alt="Product name"
        src={data?.ImageSrc}
      />
      <TextBox
        className="product-name"
        inputAttr={nameLabel}
        defaultValue={data?.Name}
        readOnly={true}
      />
    </div>
  );
}

// Demos/SelectBox/Overview/Vue/Field.vue
<template>
  <div class="custom-item">
    <img
      v-if="fieldData"
      alt="Product name"
      :src="fieldData.ImageSrc"
    >
    <DxTextBox
      :value="fieldData && fieldData.Name"
      :read-only="true"
      :input-attr="{ 'aria-label': 'Name' }"
      class="product-name"
    />
  </div>
</template>
<script>
import DxTextBox from 'devextreme-vue/text-box';

export default {
  components: {
    DxTextBox,
  },
  props: {
    fieldData: {
      type: Object,
      default: () => {},
    },
  },
};
</script>
