// apps/demos/Demos/SelectBox/CustomizeDropDownButton/React/item.tsx
import React from 'react';

interface ItemProps {
  IconSrc: string;
  Name: string;
}

export default function Item({ IconSrc, Name }: ItemProps) {
  return (
    <div className="custom-item">
      <img
        alt={Name}
        src={`../../../../images/icons/${IconSrc}`}
      />
      <div className="product-name">{Name}</div>
    </div>
  );
}

// Demos/SelectBox/Overview/Vue/Item.vue
<template>
  <div class="custom-item">
    <img
      alt="Product name"
      :src="itemData.ImageSrc"
    >
    <div class="product-name">
      {{ itemData.Name }}
    </div>
  </div>
</template>
<script>
export default {
  props: {
    itemData: {
      type: Object,
      default: () => {},
    },
  },
};
</script>
