// playgrounds/angular/src/app/examples/themes/themes-scoped-example.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'dx-themes-scoped-example',
  template: `
    <div class="example">
      <div class="example__title">
        Component styled by global theme:
      </div>
      <div class="example__control">
        <dx-radio-group>
          <dx-radio-button
            *ngFor="let option of options"
            [label]="'Option ' + option"
            [value]="option"
          ></dx-radio-button>
        </dx-radio-group>
      </div>
    </div>

    <div class="example">
      <div class="example__title">
        Component styled by scoped purple theme:
      </div>
      <div class="example__control dx-material-purple-light">
        <dx-radio-group
        >
          <dx-radio-button
            *ngFor="let option of options"
            [label]="'Option ' + option"
            [value]="option"
          ></dx-radio-button>
        </dx-radio-group>
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ThemesScopedExampleComponent {
  options = [0, 1, 2];
}

// playgrounds/react/src/examples/themes/themes-scoped-example.tsx
import { RadioButton, RadioGroup } from '@devextreme/react';
import '@devextreme/styles/lib/themes/material-purple-light-scoped.css';

const OPTIONS = [0, 1, 2];
export function ThemesScopedExample() {
  return (
    <>
      <div className="example">
        <div className="example__title">
          Component styled by global theme:
        </div>
        <div className="example__control">
          <RadioGroup>
            {OPTIONS.map((option) => (
              <RadioButton
                key={option}
                value={option}
                label={`Option  ${option.toString()}`}
              />
            ))}
          </RadioGroup>
        </div>
      </div>

      <div className="example">
        <div className="example__title">
          Component styled by scoped purple theme:
        </div>
        <div className="example__control dx-material-purple-light">
          <RadioGroup>
            {OPTIONS.map((option) => (
              <RadioButton
                key={option}
                value={option}
                label={`Option  ${option.toString()}`}
              />
            ))}
          </RadioGroup>
        </div>
      </div>
    </>
  );
}
