// apps/demos/Demos/CardView/FieldTemplate/Vue/Progress.vue
<template>
    <div className="task__progress">
        <DxProgressBar
            :value="value"
            :element-attr="{ 'aria-label': 'Progress Bar' }"
            :statusFormat="(ratio) => `${ratio * 100}%`"
        />
    </div>
</template>

<script setup lang="ts">
import { DxProgressBar } from 'devextreme-vue/progress-bar';

const props = defineProps<{
  value: number,
}>();
</script>

<style>
.task__progress {
  padding-top: 4px;
}
</style>

// apps/demos/Demos/CardView/FieldTemplate/ReactJs/Progress.js
import React from 'react';
import { ProgressBar } from 'devextreme-react/progress-bar';

const elementAttr = { 'aria-label': 'Progress Bar' };
const Progress = ({ value }) => (
  <div className="task__progress">
    <ProgressBar
      value={value}
      elementAttr={elementAttr}
      statusFormat={(ratio) => `${ratio * 100}%`}
    ></ProgressBar>
  </div>
);
export default Progress;
