// apps/demos/Demos/DataGrid/AIPoweredDetailView/Vue/DetailView.vue
<template>
  <div class="input-container">
    <div class="prompt-container">
      <DxTextBox
        placeholder="Ask AI Assistant..."
        styling-mode="filled"
        value-change-event="input"
        v-model:value="promptValue"
        @enter-key="onSubmit"
        :element-attr="promptElementAttr"
        :disabled="isLoading"
      />

      <DxButtonGroup
        :items="suggestions"
        styling-mode="outlined"
        selection-mode="none"
        @item-click="onSuggestionClick"
        :element-attr="suggestionsElementAttr"
        :disabled="isLoading"
      />
    </div>

    <div class="submit-container">
      <DxButton
        icon="sparkle"
        :text="submitButtonText"
        type="default"
        :disabled="!promptValue || isLoading"
        @click="onSubmit"
      />
    </div>
  </div>

  <div class="output-container">
    <DxTextArea
      :value="responseValue"
      :auto-resize-enabled="true"
      width="100%"
      :min-height="outputAreaMinHeight"
      :max-height="outputAreaMaxHeight"
      :read-only="true"
      :disabled="isLoading || !responseValue"
      styling-mode="outlined"
      :hover-state-enabled="false"
      :focus-state-enabled="false"
      :element-attr="responseElementAttr"
      :input-attr="responseInputAttr"
    />

    <DxLoadPanel
      container=".output-container"
      :show-pane="false"
      :shading="true"
      message=""
      :visible="isLoading"
    >
      <DxPosition of=".output-container"/>
    </DxLoadPanel>

    <div
      v-if="!isLoading && !responseValue && !isError"
      class="output-initial-message"
    >
      AI Assistant is ready to answer your questions about this record.
    </div>

    <div
      v-if="!isLoading && !responseValue && isError"
      class="output-error-message"
    >
      <span class="dx-icon-warning"/>
      An unexpected error occurred. Please try again.
    </div>
  </div>
</template>

<script setup lang="ts">
import { onUnmounted, ref } from 'vue';
import { DxTextBox, type DxTextBoxTypes } from 'devextreme-vue/text-box';
import { DxButtonGroup, type DxButtonGroupTypes } from 'devextreme-vue/button-group';
import { DxButton, type DxButtonTypes } from 'devextreme-vue/button';
import { DxTextArea } from 'devextreme-vue/text-area';
import { DxLoadPanel, DxPosition } from 'devextreme-vue/load-panel';
import { type DxEvent } from 'devextreme/events';
import themes from 'devextreme/ui/themes';
import { getAIResponse, SYSTEM_PROMPT, type AIMessage } from './service.ts';
import type { DetailViewProps } from './types.ts';

const props = defineProps<DetailViewProps>();
const { rowData, registerAbortRequest, unregisterAbortRequest } = props;

const abortController = ref<AbortController | null>(null);

const abortRequest = () => abortController.value?.abort();

registerAbortRequest(abortRequest);

onUnmounted(() => {
  abortRequest();
  unregisterAbortRequest(abortRequest);
});

const promptElementAttr = { class: 'prompt-editor' };
const suggestionsElementAttr = { class: 'dx-chat-suggestions' };
const responseElementAttr = { class: 'response-editor' };
const responseInputAttr = { 'aria-label': 'AI Response' };

const suggestions = [
  { type: 'default', text: '✨ Summary', prompt: 'Display general information about this vehicle and its features.' },
  { type: 'default', text: '⚡ Ideal Buyer', prompt: 'Describe who this vehicle appeals to the most in a sentence.' },
  { type: 'default', text: '🏎️ Competitors', prompt: 'List 2-3 models that directly compete with this vehicle.' },
];

const getTheme = () => {
  const themeName = themes.current();

  return {
    isCompact: themeName.endsWith('compact'),
    isMaterial: themeName.startsWith('material'),
    isGeneric: themeName.startsWith('generic'),
  };
};

const outputAreaMinHeight = (() => {
  const { isCompact, isMaterial } = getTheme();

  if (isMaterial) return isCompact ? 60 : 68;

  return isCompact ? 42 : 56;
})();

const outputAreaMaxHeight = (() => {
  const { isCompact, isMaterial, isGeneric } = getTheme();

  if (isMaterial) return isCompact ? 200 : 244;

  if (isGeneric) return isCompact ? 154 : 178;

  return isCompact ? 154 : 196;
})();

const promptValue = ref('');
const responseValue = ref('');
const isLoading = ref(false);
const isError = ref(false);
const submitButtonText = ref('Submit');

async function handleSubmit(event?: DxEvent) {
  if (!promptValue.value) return;

  const controller = new AbortController();
  abortController.value = controller;
  isError.value = false;
  isLoading.value = true;
  (event?.target as HTMLElement)?.blur();

  try {
    const messages: AIMessage[] = [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: `User prompt: ${promptValue.value}\nRow data: ${JSON.stringify(rowData)}` },
    ];

    const aiResponse = await getAIResponse(messages, controller.signal);

    if (aiResponse === '') throw new Error('AI response is empty');
    responseValue.value = aiResponse;
  } catch {
    responseValue.value = '';
    isError.value = true;
  } finally {
    abortController.value = null;
    submitButtonText.value = 'Resubmit';
    isLoading.value = false;
    (event?.target as HTMLElement)?.focus();
  }
}

function onSubmit({ event }: DxTextBoxTypes.EnterKeyEvent | DxButtonTypes.ClickEvent) {
  handleSubmit(event);
}

function onSuggestionClick({ itemData: suggestion, event }: DxButtonGroupTypes.ItemClickEvent) {
  promptValue.value = suggestion.prompt;
  handleSubmit(event);
}
</script>

<style>
.input-container {
  display: flex;
  border: 1px solid var(--dx-color-border);
  border-radius: var(--dx-border-radius);
  padding: 12px;
  margin-bottom: 16px;
  gap: 12px;
}

.input-container .dx-chat-suggestions {
  padding: 12px 0 0 0;
}

.input-container .dx-chat-suggestions .dx-buttongroup-item.dx-button {
  border-radius: 32px;
}

.prompt-container {
  flex-grow: 1;
}

.prompt-editor {
  height: var(--dx-component-height);
}

.output-container {
  display: grid;
  align-items: center;
  border: 1px solid var(--dx-color-border);
  border-radius: var(--dx-border-radius);
  background-color: var(--dx-datagrid-row-alternation-bg);
}

.output-container>* {
  grid-row: 1;
  grid-column: 1;
}

.output-container .response-editor {
  border: none;
  background-color: var(--dx-datagrid-row-alternation-bg);
}

.output-container .response-editor.dx-texteditor:not(.dx-state-disabled) .dx-texteditor-input {
  color: var(--dx-color-text);
}

.output-initial-message {
  text-align: center;
  white-space: pre-wrap;
  margin-left: 8px;
  margin-right: 8px;
  color: var(--dx-color-icon);
  z-index: 1;
}

.output-error-message {
  text-align: center;
  white-space: pre-wrap;
  margin-left: 8px;
  margin-right: 8px;
  color: var(--dx-color-danger);
  z-index: 1;
}

.output-error-message .dx-icon-warning {
  font-size: 20px;
  margin-right: 4px;
  vertical-align: middle;
}

.dx-theme-material {
  .submit-container {
    height: var(--dx-component-height);
    align-content: center;
  }

  .output-container .response-editor {
    box-shadow: none;
  }
}

.dx-theme-generic {
  .output-initial-message {
    color: #757575;
  }
}
</style>

// apps/demos/Demos/DataGrid/AIPoweredDetailView/React/DetailView.tsx
import React, { useCallback, useMemo, useRef, useState } from 'react';

import { type DataGridTypes } from 'devextreme-react/data-grid';
import { TextBox, type TextBoxTypes } from 'devextreme-react/text-box';
import { ButtonGroup, type ButtonGroupTypes } from 'devextreme-react/button-group';
import { Button, type ButtonTypes } from 'devextreme-react/button';
import { TextArea } from 'devextreme-react/text-area';
import { LoadPanel, Position } from 'devextreme-react/load-panel';
import { type DxEvent } from 'devextreme/events';
import themes from 'devextreme/ui/themes';
import { getAIResponse, SYSTEM_PROMPT } from './service.ts';
import { type AIMessage } from './types.ts';

type DetailViewProps = DataGridTypes.MasterDetailTemplateData & {
  onAbortReady: (abortRequest: () => void) => void;
};

const promptElementAttr = { class: 'prompt-editor' };
const suggestionsElementAttr = { class: 'dx-chat-suggestions' };
const responseElementAttr = { class: 'response-editor' };
const responseInputAttr = { 'aria-label': 'AI Response' };

const suggestions = [
  { type: 'default', text: '✨ Summary', prompt: 'Display general information about this vehicle and its features.' },
  { type: 'default', text: '⚡ Ideal Buyer', prompt: 'Describe who this vehicle appeals to the most in a sentence.' },
  { type: 'default', text: '🏎️ Competitors', prompt: 'List 2-3 models that directly compete with this vehicle.' },
];

const DetailView = ({ data: templateData, onAbortReady }: DetailViewProps) => {
  const abortControllerRef = useRef<AbortController | null>(null);
  const [promptValue, setPromptValue] = useState('');
  const [responseValue, setResponseValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isError, setIsError] = useState(false);
  const [submitButtonText, setSubmitButtonText] = useState('Submit');

  const getTheme = useCallback(() => {
    const themeName = themes.current();

    return {
      isCompact: themeName.endsWith('compact'),
      isMaterial: themeName.startsWith('material'),
      isGeneric: themeName.startsWith('generic')
    };
  }, []);

  const outputAreaMinHeight = useMemo(() => {
    const { isCompact, isMaterial } = getTheme();

    if (isMaterial) return isCompact ? 60 : 68;

    return isCompact ? 42 : 56;
  }, [getTheme]);

  const outputAreaMaxHeight = useMemo(() => {
    const { isCompact, isMaterial, isGeneric } = getTheme();

    if (isMaterial) return isCompact ? 200 : 244;

    if (isGeneric) return isCompact ? 154 : 178;

    return isCompact ? 154 : 196;
  }, [getTheme]);

  const handlePromptChange = useCallback((value: string) => {
    setPromptValue(value);
  }, []);

  const handleSubmit = useCallback(async (event?: DxEvent, prompt?: string) => {
    if (!prompt) return;

    const controller = new AbortController();
    abortControllerRef.current = controller;
    onAbortReady(() => controller.abort());

    setIsError(false);
    setIsLoading(true);
    (event?.target as HTMLElement)?.blur();

    try {
      const rowData = templateData.data;
      const messages: AIMessage[] = [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: `User prompt: ${prompt}\nRow data: ${JSON.stringify(rowData)}` },
      ];

      const aiResponse = await getAIResponse(messages, controller.signal);

      if (aiResponse === '') throw new Error('AI response is empty');
      setResponseValue(aiResponse);
    } catch {
      setResponseValue('');
      setIsError(true);
    } finally {
      abortControllerRef.current = null;
      onAbortReady(() => {});

      setSubmitButtonText('Resubmit');
      setIsLoading(false);
      (event?.target as HTMLElement)?.focus();
    }
  }, [templateData.data]);

  const onSubmit = useCallback((e: TextBoxTypes.EnterKeyEvent | ButtonTypes.ClickEvent) => {
    handleSubmit(e.event, promptValue);
  }, [promptValue, handleSubmit]);

  const onSuggestionClick = useCallback((e: ButtonGroupTypes.ItemClickEvent) => {
    const { itemData: suggestion, event } = e;
    setPromptValue(suggestion.prompt);
    handleSubmit(event, suggestion.prompt)
  }, [handleSubmit]);

  return (<>
    <div className="input-container">
      <div className="prompt-container">
        <TextBox
          placeholder="Ask AI Assistant..."
          stylingMode="filled"
          valueChangeEvent="input"
          value={promptValue}
          onValueChange={handlePromptChange}
          onEnterKey={onSubmit}
          elementAttr={promptElementAttr}
          disabled={isLoading}
        />

        <ButtonGroup
          items={suggestions}
          stylingMode="outlined"
          selectionMode="none"
          onItemClick={onSuggestionClick}
          elementAttr={suggestionsElementAttr}
          disabled={isLoading}
        />
      </div>

      <div className="submit-container">
        <Button
          icon="sparkle"
          text={submitButtonText}
          type="default"
          disabled={!promptValue || isLoading}
          onClick={onSubmit}
        />
      </div>
    </div>

    <div className="output-container">
      <TextArea
        value={responseValue}
        autoResizeEnabled={true}
        width="100%"
        minHeight={outputAreaMinHeight}
        maxHeight={outputAreaMaxHeight}
        readOnly={true}
        disabled={isLoading || !responseValue}
        stylingMode="outlined"
        hoverStateEnabled={false}
        focusStateEnabled={false}
        elementAttr={responseElementAttr}
        inputAttr={responseInputAttr}
      />

      <LoadPanel
        container=".output-container"
        showPane={false}
        shading={true}
        message=""
        visible={isLoading}
      >
        <Position of=".output-container" />
      </LoadPanel>

      {
        !isLoading && !responseValue && !isError && (
          <div className="output-initial-message">
            AI Assistant is ready to answer your questions about this record.
          </div>
        )
      }

      {
        !isLoading && !responseValue && isError && (
          <div className="output-error-message">
            <span className="dx-icon-warning"></span>
            An unexpected error occurred. Please try again.
          </div>
        )
      }
    </div>
  </>);
};

export default DetailView;
