// Demos/DataGrid/SignalRService/React/ChangeCell.js
import React from 'react';

const ChangeCell = (cell) => (
  <div className={cell.data.change > 0 ? 'inc' : 'dec' }>
    <span className="current-value">{cell.text}</span>
    <span className="arrow"></span>
    <span className="diff">{cell.data.percentChange.toFixed(2)}%</span>
  </div>
);

export default ChangeCell;

// Demos/DataGrid/SignalRService/Vue/ChangeCell.vue
<template>
  <div :class="{ inc: cellData.data.change > 0, dec: cellData.data.change < 0 }">
    <span class="current-value">{{ cellData.text }}</span>
    <span class="arrow"/>
    <span class="diff">{{ cellData.data.percentChange.toFixed(2) }}%</span>
  </div>
</template>

<script>
export default {
  props: {
    cellData: {
      type: Object,
      default: () => {},
    },
  },
};
</script>
