// apps/demos/Demos/DataGrid/AIColumns/React/Trademark.tsx
import React, { useCallback } from 'react';
import { type Vehicle } from './types';

type TrademarkProps = {
  vehicle: Vehicle;
  onShowInfo: (vehicle: Vehicle) => void;
};

export default function Trademark({ vehicle, onShowInfo }: TrademarkProps) {
  const { ID, TrademarkName, Name } = vehicle;

  const onKeyDown = useCallback((event: React.KeyboardEvent<HTMLImageElement>) => {
    if (event.key === 'Enter') {
      onShowInfo(vehicle);
    }
  }, [onShowInfo, vehicle]);

  return (
    <div className="trademark__wrapper">
      <div className="trademark__img-wrapper">
        <img
          className="trademark__img"
          src={`../../../../images/vehicles/image_${ID}.png`}
          alt={`${TrademarkName} ${Name}`}
          tabIndex={0}
          onClick={() => onShowInfo(vehicle)}
          role="button"
          onKeyDown={onKeyDown}
          aria-haspopup="dialog"
          aria-label={`${TrademarkName} ${Name} - press Enter for image info`}
        />
      </div>
      <div>
        <div className="trademark__text trademark__text--title">{TrademarkName}</div>
        <div className="trademark__text trademark__text--subtitle">{Name}</div>
      </div>
    </div>
  );
}

// apps/demos/Demos/DataGrid/AIColumns/Angular/app/trademark/trademark.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'trademark',
  templateUrl: './trademark.component.html',
  styleUrls: ['./trademark.component.css'],
})
export class Trademark {
  @Input() id!: number;

  @Input() name!: string;

  @Input() trademarkName!: string;

  @Output() showInfo = new EventEmitter<void>();

  onKeyDown = (event: KeyboardEvent) => {
    if (event.key === 'Enter') {
      this.showInfo.emit();
    }
  };
}

<div class="trademark__wrapper">
  <div class="trademark__img-wrapper">
    <img
      class="trademark__img"
      src="../../../../images/vehicles/image_{{ id }}.png"
      alt="{{ trademarkName }} {{ name }}"
      (click)="showInfo.emit()"
      (keydown)="onKeyDown($event)"
      role="button"
      tabindex="0"
      [attr.aria-haspopup]="'dialog'"
      [attr.aria-label]="
        trademarkName + ' ' + name + ' - press Enter for image info'
      "
    />
  </div>
  <div class="trademark__text-wrapper">
    <div class="trademark__text trademark__text--title">{{
      trademarkName
    }}</div>
    <div class="trademark__text trademark__text--subtitle">{{ name }}</div>
  </div>
</div>
