// apps/demos/Demos/Toast/Overview/Vue/ProductItem.vue
<template>
  <li>
    <img
      :alt="product.Name"
      :src="product.ImageSrc"
    >
    <br>
    <div>{{ product.Name }}</div>
    <DxCheckBox
      @value-changed="onValueChanged"
      text="Available"
    />
  </li>
</template>
<script setup lang="ts">
import { DxCheckBox } from 'devextreme-vue/check-box';
import { products } from './data.ts';

type Product = typeof products[0];

const props = withDefaults(defineProps<{
  product: Product,
}>(), {
  product: () => ({} as Product),
});

const emit = defineEmits(['checked']);

function onValueChanged(e) {
  emit('checked', e, props.product);
}
</script>

// apps/demos/Demos/Toast/Overview/ReactJs/ProductItem.js
import React, { useCallback } from 'react';
import { CheckBox } from 'devextreme-react/check-box';

export function ProductItem({ product, checkAvailability }) {
  const onValueChanged = useCallback(
    (e) => {
      checkAvailability(e, product);
    },
    [product, checkAvailability],
  );
  return (
    <>
      <img
        alt={product.Name}
        src={product.ImageSrc}
      />
      <div>{product.Name}</div>
      <CheckBox
        text="Available"
        onValueChanged={onValueChanged}
      />
    </>
  );
}
