// playgrounds/react/src/examples/themes/themes-dynamic-example.tsx
import { RadioButton, RadioGroup } from '@devextreme/react';

import '@devextreme/styles/lib/themes/material-blue-light-scoped.css';
import { useState } from 'react';

const THEMES = ['blue', 'purple'];

export function ThemesDynamicExample(): JSX.Element {
  const [theme, setTheme] = useState(THEMES[0]);

  // In real demo we can replace static import to fetch and link injection:
  // const cssText = await fetch('@devextreme/styles/lib/themes/material-blue-light-scoped.css');
  // const link = document.getElementById('theme-style') || document.createElement('style');
  // style.innerText = cssText;
  const handleChange = (themeName?: string) => {
    setTheme(themeName ?? THEMES[0]);
  };

  return (
    <div className={`example dx-material-${theme}-light`}>
      <div className="example__title" style={{ color: 'var(--primary-900)' }}>
        Dynamic theme change example:
      </div>
      <div className="example__control">
        <RadioGroup defaultValue={THEMES[0]} valueChange={handleChange}>
          { THEMES.map((themeName) => (
            <RadioButton
              key={themeName}
              label={`Theme ${themeName}`}
              value={themeName}
            />
          ))}
        </RadioGroup>
      </div>
    </div>
  );
}

// playgrounds/angular/src/app/examples/themes/themes-dynamic-example.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'dx-themes-dynamic-example',
  template: `
    <div class="example"
         [class.dx-material-blue-light]="value === 'blue'"
         [class.dx-material-purple-light]="value === 'purple'">
      <div class="example__title title--themed">
        Dynamic theme change example:
      </div>
      <div class="example__control">
        <dx-radio-group [(value)]="value">
          <dx-radio-button
            *ngFor="let theme of themes"
            [label]="'Theme ' + theme"
            [value]="theme"
          ></dx-radio-button>
        </dx-radio-group>
      </div>
    </div>`,
  styles: [`
    .title--themed {
      color: var(--primary-900);
    }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ThemesDynamicExampleComponent {
  themes = ['blue', 'purple'];

  value? = this.themes[0];
}
