// apps/demos/Demos/List/ItemTemplate/React/ProductInfo.tsx
import React from 'react';
import type { Product } from './types';

const currencyFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  minimumFractionDigits: 0,
  maximumFractionDigits: 0,
});

export default function ProductInfo(item: Product) {
  const {
    Name,
    ImageSrc,
    Price,
  } = item;

  return (
    <div className="product">
      <img alt={Name} src={ImageSrc} />
      <div>{Name}</div>
      <div className="price">{currencyFormatter.format(Price)}</div>
    </div>
  );
}

// Demos/List/ItemTemplate/Vue/ProductInfo.vue
<template>
  <div>
    <div class="product">
      <img
        :alt="item.Name"
        :src="item.ImageSrc"
      >
      <div>{{ item.Name }}</div>
      <div class="price">{{ currency(item.Price) }}</div>
    </div>
  </div>
</template>
<script>

const currencyFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  minimumFractionDigits: 0,
  maximumFractionDigits: 0,
});

export default {
  props: {
    item: {
      type: Object,
      default: () => {},
    },
  },
  methods: {
    currency(data) {
      return currencyFormatter.format(data);
    },
  },
};
</script>
<style scoped>
.product {
  height: 65px;
}

.product > img {
  height: 100%;
  width: 95px;
  float: left;
}

.product > div {
  padding-left: 10px;
  vertical-align: top;
  line-height: 65px;
  font-size: 15px;
  float: left;
}

.product > div.price {
  float: right;
  font-size: 18px;
}
</style>
