// Demos/Scheduler/Overview/React/DataCell.js
import React from 'react';

const isWeekEnd = (date) => {
  const day = date.getDay();
  return day === 0 || day === 6;
};

const getCurrentTraining = (date, employeeID) => {
  const result = (date + employeeID) % 3;
  const currentTraining = `training-background-${result}`;

  return currentTraining;
};

const DataCell = (props) => {
  const { data: { startDate, groups: { employeeID }, text } } = props;

  const dayClasses = [
    'day-cell',
    getCurrentTraining(startDate.getDate(), employeeID),
  ];

  const employeeClasses = [`employee-${employeeID}`, 'dx-template-wrapper'];
  if (isWeekEnd(startDate)) {
    employeeClasses.push(`employee-weekend-${employeeID}`);
  }

  return (
    <div className={employeeClasses.join(' ')}>
      <div className={dayClasses.join(' ')}>
        {text}
      </div>
    </div>
  );
};

export default DataCell;

// apps/demos/Demos/Scheduler/Overview/Vue/DataCell.vue
<template>
  <div
    :class="markWeekEnd(cellData)"
  >
    <div :class="markTraining(cellData)">
      {{ cellData.text }}
    </div>
  </div>
</template>
<script setup lang="ts">
withDefaults(defineProps<{
  cellData?: any
}>(), {
  cellData: () => {},
});

function markWeekEnd(cellData) {
  function isWeekEnd(date) {
    const day = date.getDay();
    return day === 0 || day === 6;
  }
  const classObject = {};
  classObject[`employee-${cellData.groups.employeeID}`] = true;
  classObject[`employee-weekend-${cellData.groups.employeeID}`] = isWeekEnd(cellData.startDate);
  return classObject;
}
function markTraining(cellData) {
  const classObject = {
    'day-cell': true,
  };

  classObject[
    getCurrentTraining(cellData.startDate.getDate(), cellData.groups.employeeID)
  ] = true;
  return classObject;
}
function getCurrentTraining(date, employeeID) {
  const result = (date + employeeID) % 3;
  const currentTraining = `training-background-${result}`;

  return currentTraining;
}
</script>
<style>
.day-cell {
  width: 100%;
  height: 100%;
  background-position: center center;
  background-repeat: no-repeat;
}

.employee-1 {
  background-color: rgba(55, 126, 58, 0.08);
}

.employee-2 {
  background-color: rgba(194, 81, 0, 0.08);
}

.employee-weekend-1 {
  background-color: rgba(55, 126, 58, 0.12);
}

.employee-weekend-2 {
  background-color: rgba(194, 81, 0, 0.12);
}

.training-background-0 {
  background-image: url("../../../../images/gym/icon-abs.png");
}

.training-background-1 {
  background-image: url("../../../../images/gym/icon-step.png");
}

.training-background-2 {
  background-image: url("../../../../images/gym/icon-fitball.png");
}
</style>
