// packages/angular/projects/angular/src/components/slideToggle/views/dx-slide-toggle-indicator-view.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { SlideToggleState } from '@devexpress/core/src/components/slideToggle';
import { DxViewModelContracts } from '../../../internal/index';

@Component({
  template: '',
})
export abstract class DxSlideToggleIndicatorViewContracts
  extends DxViewModelContracts<SlideToggleState> {
}

@Component({
  selector: 'dx-slide-toggle-indicator-view',
  template: `
    <div class="dx-slide-toggle-indicator"
         [class.-left]="viewModel.config.textPosition === 'right'"
         [class.-right]="viewModel.config.textPosition === 'left'">
      <div class="dx-slide-toggle-line"
           [class.-off]="!viewModel.model.value"
           [class.-on]="viewModel.model.value">
        <div class="dx-slide-toggle-thumb"
             [class.-off]="!viewModel.model.value"
             [class.-on]="viewModel.model.value">
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./dx-slide-toggle-indicator-view.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxSlideToggleIndicatorViewComponent extends DxSlideToggleIndicatorViewContracts {
}

// packages/react/src/components/slideToggle/views/dxSlideToggleIndicatorView.tsx
import React from 'react';
import { TTextPosition } from '@devexpress/core/slideToggle';

import './dxSlideToggleIndicatorView.scss';

interface DxSlideToggleIndicatorViewProps {
    // TODO jQuery: Temporary wrapping for the inferno generator.
    data: {
        value: boolean;
        textPosition: TTextPosition;
    }
}

const DxSlideToggleIndicatorView = ({
    data: {
        value,
        textPosition
    }
}: DxSlideToggleIndicatorViewProps) => {
    return (
        <div
            className={`dx-slide-toggle-indicator ${textPosition === 'right' ? '-left' : '-right'}`}>
            <div className={`dx-slide-toggle-line ${!value ? '-off' : '-on'}`}>
                <div className={`dx-slide-toggle-thumb ${!value ? '-off' : '-on'}`}>
                </div>
            </div>
        </div>
    );
};

export type { DxSlideToggleIndicatorViewProps };
export { DxSlideToggleIndicatorView };
