// Demos/Scheduler/CellTemplates/React/DataCell.js
import React from 'react';
import Utils from './utils.js';

export default function DataCell(props) {
  const { startDate } = props.itemData;
  const isDisableDate = Utils.isHoliday(startDate) || Utils.isWeekend(startDate);
  const isDinner = Utils.isDinner(startDate);
  let cssClasses = props.className
    ? props.className
    : '';

  if (isDisableDate) {
    cssClasses += ' disable-date';
  } else if (isDinner) {
    cssClasses += ' dinner';
  }

  return (
    <div className={cssClasses}>
      {props.children}
    </div>
  );
}

// apps/demos/Demos/Scheduler/CellTemplates/Vue/DataCell.vue
<template>
  <div :class="markDataCell(cellData)">
    <slot/>
  </div>
</template>
<script setup lang="ts">
import Utils from './utils.ts';

withDefaults(defineProps<{
  cellData?: any
}>(), {
  cellData: () => {},
});

function markDataCell(cellData) {
  const date = cellData.startDate;
  const isDisableDate = Utils.isHoliday(date) || Utils.isWeekend(date);
  const isDinner = !isDisableDate && Utils.isDinner(date);

  return {
    'disable-date': isDisableDate,
    dinner: isDinner,
  };
}
</script>
