// apps/demos/Demos/Scheduler/CellTemplates/ReactJs/DataCellMonth.js
import React from 'react';
import DataCell from './DataCell.js';

const DataCellMonth = (props) => {
  const { startDate } = props.data;
  return (
    <DataCell
      data={props.data}
      className="dx-scheduler-date-table-cell-text"
    >
      {startDate.getDate()}
    </DataCell>
  );
};
export default DataCellMonth;

// apps/demos/Demos/Scheduler/CellTemplates/Vue/DataCellMonth.vue
<template>
  <DataCell
    class="dx-scheduler-date-table-cell-text"
    :cell-data="cellData"
  >
    {{ day() }}
  </DataCell>
</template>
<script setup lang="ts">
import DataCell from './DataCell.vue';

const props = defineProps<{
  cellData: Record<string, any>
}>();

function day() {
  return props.cellData.startDate.getDate();
}
</script>
