// apps/demos/Demos/Diagram/CustomShapesWithTemplatesWithEditing/ReactJs/CustomShapeToolboxTemplate.js
import React from 'react';

export default function CustomShapeToolboxTemplate() {
  return (
    <svg className="template">
      <text
        x="50%"
        y="40%"
      >
        New
      </text>
      <text
        x="50%"
        y="70%"
      >
        Employee
      </text>
    </svg>
  );
}

// demos/Demos/Diagram/CustomShapesWithTemplatesWithEditing/Vue/CustomShapeToolboxTemplate.vue
<template>
  <svg class="template">
    <text
      x="50%"
      y="40%"
    >
      New
    </text>
    <text
      x="50%"
      y="70%"
    >
      Employee
    </text>
  </svg>
</template>

<script setup lang="ts">
// for SFC compiler
</script>

<style>
    #diagram .template .template-name {
      font-weight: bold;
      text-decoration: underline;
    }

    #diagram .template .template-title {
      font-style: italic;
    }
</style>
