// Demos/Scheduler/CurrentTimeIndicator/Vue/AppointmentTemplate.vue
<template>
  <div class="movie">
    <img :src="movieInfo.image">
    <div class="movie-text">{{ movieInfo.text }}</div>
  </div>
</template>

<script>
import Query from 'devextreme/data/query';

import { moviesData } from './data.js';

const getMovieInfo = function(data) {
  return Query(moviesData)
    .filter('id', data.movieId)
    .toArray()[0] || {};
};

export default {
  props: {
    appointmentModel: {
      type: Object,
      default: () => { }
    }
  },
  data() {
    return {
      moviesData: moviesData,
      movieInfo: getMovieInfo(this.appointmentModel.appointmentData)
    };
  }
};
</script>

// apps/demos/Demos/Scheduler/CurrentTimeIndicator/ReactJs/AppointmentTemplate.js
import React from 'react';
import Query from 'devextreme/data/query';
import { moviesData } from './data.js';

const getMovieById = (id) => Query(moviesData).filter(['id', id]).toArray()[0];
const AppointmentTemplate = (props) => {
  const { appointmentData } = props.data;
  const movieInfo = getMovieById(appointmentData.movieId) || {};
  return (
    <div className="movie">
      <img src={movieInfo.image} />
      <div className="movie-text">{movieInfo.text}</div>
    </div>
  );
};
export default AppointmentTemplate;
