// apps/demos/Demos/Toast/Overview/ReactJs/ProductItem.js
import React, { useCallback } from 'react';
import { CheckBox } from 'devextreme-react/check-box';

export function ProductItem({ product, checkAvailability }) {
  const onValueChanged = useCallback(
    (e) => {
      checkAvailability(e, product);
    },
    [product, checkAvailability],
  );
  return (
    <>
      <img
        alt={product.Name}
        src={product.ImageSrc}
      />
      <div>{product.Name}</div>
      <CheckBox
        text="Available"
        onValueChanged={onValueChanged}
      />
    </>
  );
}

// Demos/Toast/Overview/Vue/ProductItem.vue
<template>
  <li>
    <img
      :alt="product.Name"
      :src="product.ImageSrc"
    >
    <br>
    <div>{{ product.Name }}</div>
    <DxCheckBox
      @value-changed="onValueChanged"
      text="Available"
    />
  </li>
</template>
<script>
import { DxCheckBox } from 'devextreme-vue/check-box';

export default {
  components: {
    DxCheckBox,
  },
  props: {
    product: {
      type: Object,
      required: true,
      default: () => {},
    },
  },
  methods: {
    onValueChanged(e) {
      this.$emit('checked', e, this.product);
    },
  },
};
</script>
