// apps/demos/Demos/DataGrid/AdvancedMasterDetailView/Vue/AddressTab.vue
<template>
  <DxForm
    :form-data="data"
    :items="items"
    :col-count="2"
    :customize-item="customizeItem"
    class="address-form form-container"
  >
    <template #form-item="{ data: item }">
      <span>
        {{ item.editorOptions.value }}
      </span>
    </template>
  </DxForm>
</template>

<script setup lang="ts">
import { DxForm, type DxFormTypes } from 'devextreme-vue/form';
import { type Supplier } from './data.ts';

defineProps<{
  data: Supplier
}>();

const items = [
  { dataField: 'Address'},
  { dataField: 'City'},
  { dataField: 'Region'},
  { dataField: 'PostalCode'},
  { dataField: 'Country'},
  { dataField: 'Phone' },
];

const customizeItem = (item: DxFormTypes.SimpleItem) => {
  item.template = 'form-item';
};
</script>

// Demos/DataGrid/AdvancedMasterDetailView/ReactJs/AddressTab.js
import React from 'react';
import { Form, Item } from 'devextreme-react/form';

const items = ['Address', 'City', 'Region', 'PostalCode', 'Country', 'Phone'];
const renderFormItem = (item) => <span>{item.editorOptions.value}</span>;
const AddressTab = (props) => (
  <Form
    formData={props.data}
    colCount={2}
    className="address-form form-container"
  >
    {items.map((item, index) => (
      <Item
        dataField={item}
        key={index}
        render={renderFormItem}
      />
    ))}
  </Form>
);
export default AddressTab;
