// apps/demos/Demos/DataGrid/MasterDetailView/React/DetailTemplate.tsx
import React from 'react';

import { DataGrid, Column } from 'devextreme-react/data-grid';
import type { DataGridTypes } from 'devextreme-react/data-grid';
import { ArrayStore, DataSource } from 'devextreme-react/common/data';

import { tasks } from './data.ts';
import type { Task } from './data.ts';

const getTasks = (key: number) => new DataSource({
  store: new ArrayStore({
    data: tasks,
    key: 'ID',
  }),
  filter: ['EmployeeID', '=', key],
});

const completedValue = (rowData: Task) => rowData.Status === 'Completed';

const DetailTemplate = (props: DataGridTypes.MasterDetailTemplateData) => {
  const { FirstName, LastName } = props.data.data;
  const dataSource = getTasks(props.data.key);

  return (
    <>
      <div className="master-detail-caption">
        {`${FirstName} ${LastName}'s Tasks:`}
      </div>
      <DataGrid
        dataSource={dataSource}
        showBorders={true}
        columnAutoWidth={true}
      >
        <Column dataField="Subject" />
        <Column dataField="StartDate" dataType="date" />
        <Column dataField="DueDate" dataType="date" />
        <Column dataField="Priority" />
        <Column
          caption="Completed"
          dataType="boolean"
          calculateCellValue={completedValue}
        />
      </DataGrid>
    </>
  );
};

export default DetailTemplate;

// apps/demos/Demos/DataGrid/MasterDetailView/Vue/DetailTemplate.vue
<template>
  <div>
    <div class="master-detail-caption">{{ detailInfo }}</div>
    <DxDataGrid
      :data-source="dataSource"
      :show-borders="true"
      :column-auto-width="true"
    >
      <DxColumn data-field="Subject"/>
      <DxColumn
        data-field="StartDate"
        data-type="date"
      />
      <DxColumn
        data-field="DueDate"
        data-type="date"
      />
      <DxColumn data-field="Priority"/>
      <DxColumn
        :calculate-cell-value="completedValue"
        data-type="boolean"
        caption="Completed"
      />
    </DxDataGrid>
  </div>
</template>
<script setup lang="ts">
import { reactive } from 'vue';
import { DxDataGrid, DxColumn, DxDataGridTypes } from 'devextreme-vue/data-grid';
import { ArrayStore } from 'devextreme-vue/common/data';
import { DataSource } from 'devextreme-vue/common/data';
import { tasks, Task } from './data.ts';

const props = defineProps<{
  templateData: DxDataGridTypes.MasterDetailTemplateData
}>();

const dataSource = getTasks(props.templateData.key);

const itemData = reactive(props.templateData.data);
const detailInfo = `${itemData.FirstName} ${itemData.LastName}'s Tasks:`;

const completedValue = (rowData: Task) => rowData.Status === 'Completed';

function getTasks(key: number) {
  return new DataSource({
    store: new ArrayStore({
      data: tasks,
      key: 'ID',
    }),
    filter: ['EmployeeID', '=', key],
  });
}
</script>
<style>
.master-detail-caption {
  padding: 0 0 5px 10px;
  font-size: 14px;
  font-weight: bold;
}
</style>
