// Demos/Scheduler/CellTemplates/Vue/DataCellMonth.vue
<template>
  <DataCell
    class="dx-scheduler-date-table-cell-text"
    :cell-data="cellData"
  >
    {{ day() }}
  </DataCell>
</template>
<script>
import DataCell from './DataCell.vue';

export default {
  components: {
    DataCell,
  },
  props: {
    cellData: {
      type: Object,
      default: () => {},
    },
  },
  methods: {
    day() {
      return this.cellData.startDate.getDate();
    },
  },
};
</script>

// Demos/Scheduler/CellTemplates/React/DataCellMonth.js
import React from 'react';
import DataCell from './DataCell.js';

const DataCellMonth = (props) => {
  const { startDate } = props.data;
  const day = startDate.getDate();

  return (
    <DataCell
      data={props.data}
      className='dx-scheduler-date-table-cell-text'
    >
      {day}
    </DataCell>
  );
};

export default DataCellMonth;
