// apps/demos/Demos/Scheduler/CellTemplates/Vue/TimeCell.vue
<template>
  <div :class="markTimeCell(cellData)">
    {{ cellData.text }}
    <div
      v-if="hasCoffeeCupIcon"
      class="cafe"
    />
  </div>
</template>
<script setup lang="ts">
import { computed } from 'vue';
import Utils from './utils.ts';

const props = withDefaults(defineProps<{
  cellData?: any
}>(), {
  cellData: () => {},
});

const hasCoffeeCupIcon = computed(() => {
  const { date } = props.cellData;
  return Utils.hasCoffeeCupIcon(date);
});

function markTimeCell(cellData) {
  return { dinner: Utils.isDinner(cellData.date) };
}
</script>

// Demos/Scheduler/CellTemplates/React/TimeCell.js
import React from 'react';
import Utils from './utils.js';

const TimeCell = (props) => {
  const { date, text } = props.data;

  const isDinner = Utils.isDinner(date);
  const hasCoffeeCupIcon = Utils.hasCoffeeCupIcon(date);

  return (
    <div className={isDinner ? 'dinner' : null}>
      {text}
      {hasCoffeeCupIcon ? <div className='cafe' /> : null}
    </div>
  );
};

export default TimeCell;
