// apps/demos/Demos/Pagination/Overview/Angular/app/employee-card/employee-card.component.ts
import { Component, Input } from '@angular/core';
import { Employee } from '../app.service';

@Component({
  selector: 'employee-card',
  templateUrl: './employee-card.component.html',
})
export class EmployeeCard {
  @Input() employee: Employee;
}

<div class="employees__img-wrapper">
  <img
    class="employees__img"
    [src]="employee.Picture"
    [alt]="employee.FullName"
  />
</div>
<div class="employees__info">
  <div class="employees__info-row">
    <span class="employees__info-label">Full Name:</span>
    <span class="employees__info-value">{{ employee.FullName }}</span>
  </div>
  <div class="employees__info-row">
    <span class="employees__info-label">Position:</span>
    <span class="employees__info-value">{{ employee.Title }}</span>
  </div>
  <div class="employees__info-row">
    <span class="employees__info-label">Phone:</span>
    <span class="employees__info-value">{{ employee.MobilePhone }}</span>
  </div>
</div>

// apps/demos/Demos/Pagination/Overview/React/EmployeeCard.tsx
import React from 'react';
import type { Employee } from './types.ts';

interface EmployeeCardProps {
  employee: Employee;
}

const EmployeeCard = ({ employee }: EmployeeCardProps) => (
  <div className="employees__card">
    <div className="employees__img-wrapper">
      <img
        className="employees__img"
        src={employee.Picture}
        alt={employee.FullName}
      />
    </div>
    <div className="employees__info">
      <div className="employees__info-row">
        <span className="employees__info-label">Full Name:</span>
        <span className="employees__info-value">{employee.FullName}</span>
      </div>

      <div className="employees__info-row">
        <span className="employees__info-label">Position:</span>
        <span className="employees__info-value">{employee.Title}</span>
      </div>

      <div className="employees__info-row">
        <span className="employees__info-label">Phone:</span>
        <span className="employees__info-value">{employee.MobilePhone}</span>
      </div>
    </div>
  </div>
);

export default EmployeeCard;
