// apps/demos/Demos/FilterBuilder/WithList/React/CustomItem.tsx
import React from 'react';

import type { Product } from './data.ts';

const currencyFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  minimumFractionDigits: 0,
  maximumFractionDigits: 0,
});

export default function CustomItem(item: Product) {
  return (
    <div className="product">
      <img
        src={item.ImageSrc}
        alt={`Picture of ${item.Name}`}
      />
      <div>{item.Name}</div>
      <div className="price">{currencyFormatter.format(item.Price)}</div>
    </div>
  );
}

// apps/demos/Demos/FilterBuilder/WithList/Vue/CustomItem.vue
<template>
  <div>
    <div class="product">
      <img
        :src="item.ImageSrc"
        :alt="'Picture of {{item.Name}}'"
      >
      <div>{{ item.Name }}</div>
      <div class="price">{{ currency(item.Price) }}</div>
    </div>
  </div>
</template>
<script setup lang="ts">
withDefaults(defineProps<{
  item?: Record<string, any>
}>(), {
  item: () => ({} as Record<string, any>),
});

const currencyFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  minimumFractionDigits: 0,
  maximumFractionDigits: 0,
});

const currency = (data: number) => currencyFormatter.format(data);
</script>
<style>
.product {
  height: 65px;
}

.product > img {
  height: 100%;
  float: left;
}

.product > div {
  padding-left: 10px;
  vertical-align: top;
  line-height: 65px;
  font-size: 15px;
  float: left;
}

.product > div.price {
  float: right;
  font-size: 18px;
}
</style>
