// apps/demos/Demos/VectorMap/CustomAnnotations/ReactJs/AnnotationTemplate.js
import React from 'react';

const getImagePath = (name) => `../../../../images/flags/${name?.replace(/\s/, '')}.svg`;
const formatNumber = new Intl.NumberFormat('en-US', {
  minimumFractionDigits: 0,
}).format;
const AnnotationTemplate = ({
  data: {
    name, capital, population, area,
  },
}) => (
  <svg className="annotation">
    <image
      href={getImagePath(name)}
      width="60"
      height="40"
    />
    <rect
      x={0}
      y={0}
      className="border"
    ></rect>
    <text
      x="70"
      y="25"
      className="state"
    >
      {name}
    </text>
    <text
      x="0"
      y="60"
    >
      <tspan className="caption">Capital:</tspan>
      <tspan
        className="capital"
        dx="5"
      >
        {capital}
      </tspan>
      <tspan
        dy="14"
        x="0"
        className="caption"
      >
        Population:
      </tspan>
      <tspan
        className="population"
        dx="5"
      >
        {formatNumber(population)}
      </tspan>
      <tspan
        dy="14"
        x="0"
        className="caption"
      >
        Area:
      </tspan>
      <tspan
        className="area"
        dx="5"
      >
        {formatNumber(area)}
      </tspan>
      <tspan dx="5">km</tspan>
      <tspan
        className="sup"
        dy="-2"
      >
        2
      </tspan>
    </text>
  </svg>
);
export default AnnotationTemplate;

// Demos/VectorMap/CustomAnnotations/Vue/AnnotationTemplate.vue
<template>
  <svg class="annotation">
    <image
      :href="getImagePath()"
      width="60"
      height="40"
    />
    <rect
      x="0"
      y="0"
      class="border"
    />
    <text
      x="70"
      y="25"
      class="state"
    >{{ data.name }}</text>
    <text
      x="0"
      y="60"
    >
      <tspan class="caption">Capital:</tspan><tspan class="capital" dx="5">{{ data.capital }}</tspan><tspan
        dy="14"
        x="0"
        class="caption"
      >Population:</tspan><tspan class="population" dx="5">{{ formatNumber(data.population) }}</tspan><tspan
        dy="14"
        x="0"
        class="caption"
      >Area:</tspan><tspan class="area" dx="5">{{ formatNumber(data.area) }}</tspan><tspan dx="5">km</tspan><tspan
        class="sup"
        dy="-2"
      >2</tspan>
    </text>
  </svg>
</template>
<script>

export default {
  props: {
    annotation: {
      type: Object,
      default: () => ({})
    }
  },
  data() {
    return {
      data: this.annotation.data
    };
  },
  methods: {
    getImagePath() {
      return `../../../../images/flags/${this.data.name.replace(/\s/, '')}.svg`;
    },
    formatNumber:  new Intl.NumberFormat('en-US', {
      minimumFractionDigits: 0
    }).format
  }
};
</script>
<style>
.annotation {
    font-size: 12px;
}
.border {
  width: 60px;
  height: 40px;
  stroke: rgba(191, 191, 191, 0.25);
  stroke-width: 1px;
  fill: transparent;
}
.state {
    font-weight: 500;
    font-size: 14px;
}
.caption {
    font-weight: 500;
}
.sup {
    font-size: 0.8em;
}
</style>
