// Demos/DataGrid/SignalRService/Vue/ChangeCell.vue
<template>
  <div :class="{ inc: cellData.data.change > 0, dec: cellData.data.change < 0 }">
    <span class="current-value">{{ cellData.text }}</span>
    <span class="arrow"/>
    <span class="diff">{{ cellData.data.percentChange.toFixed(2) }}%</span>
  </div>
</template>

<script setup lang="ts">
import { DxDataGridTypes } from 'devextreme-vue/data-grid';

defineProps<{
  cellData: DxDataGridTypes.ColumnCellTemplateData
}>();
</script>

// apps/demos/Demos/DataGrid/SignalRService/React/ChangeCell.tsx
import { DataGridTypes } from 'devextreme-react/data-grid';
import React from 'react';

const ChangeCell = (cell: DataGridTypes.ColumnCellTemplateData) => (
  <div className={cell.data.change > 0 ? 'inc' : 'dec' }>
    <span className="current-value">{cell.text}</span>
    <span className="arrow"></span>
    <span className="diff">{cell.data.percentChange.toFixed(2)}%</span>
  </div>
);

export default ChangeCell;
