// apps/demos/Demos/SelectBox/Overview/React/Field.tsx
import React from 'react';
import TextBox from 'devextreme-react/text-box';

const nameLabel = { 'aria-label': 'Name' };

export default function Field(data: { ImageSrc: any; Name: any }) {
  return (
    <div className="custom-addon">
      <img
        alt="Product name"
        src={data && data.ImageSrc}
      />
    </div>
  );
}

// apps/demos/Demos/SelectBox/Overview/Vue/Field.vue
<template>
  <div class="custom-addon">
    <img
      v-if="fieldData"
      alt="Product name"
      :src="fieldData.ImageSrc"
    >
  </div>
</template>
<script setup lang="ts">
import DxTextBox from 'devextreme-vue/text-box';

withDefaults(defineProps<{
  fieldData?: Record<string, any>
}>(), {
  fieldData: () => ({} as Record<string, any>),
});
</script>
